#import "utils.typ": *


Online Social Networks (OSNs) have evolved from simple interpersonal communication utilities into complex, socio-technical ecosystems that fundamentally govern the modern information landscape. Among various configurations, the microblogging format—pioneered by Twitter in 2006 @arrington2006twttr —introduced unique structural constraints: strict character limitations and asymmetric follower-followee topologies. This format detonated a "before and after" in how social networks were perceived and used, as it broke from the paradigm of mutual friendship (where both users must agree to be connected) into one where any user can follow any other without explicit permission. Content consumption within these networks historically relied on chronological timelines, where information propagation is efectuated through user-driven amplification mechanisms such as reposts, the action of showing a specific post to your followers.

Every change made to a microblogging platform alters the dynamics of content diffusion: which posts reach further, are seen by more people, or go viral. The introduction of algorithmic feeds, recommendation systems, and notification delivery has reshaped what users see and when. Over time, the platforms that host public discourse have accumulated immense control over not only how information flows but the way that flows: as private-equity owned business, social media platforms greatest incentives is to maximize engagment, for their users be able to be exposed to more advertisment, the main source of income of online social platforms. Needless to say, none of those has neither the end user, the discourse quality on the platfrom nor the well-being of societies on their mind, at least as a first thought.  

As the data collected by social media platforms is of high economic value, usage data and patters of users have been been shared in rare ocasions and sparsely with researchers or non-profit entities; normally its used as proxies for internal R&D inside the same companies owning the platforms to change the experience under their own criteria. Luckly, the centralization of OSNs has prompted a paradigm shift toward open, decentralized alternatives in recent years, being the most prominent examples Mastodon @mastodon-social-network and Bluesky @bluesky-social-network. The latter was founded by ex-Twitter CEO Jack Dorsey @palmer2019twitter and it's build upon the Authenticated Transfer Protocol (AT Protocol), which makes the network open by specifiying the protocols that Bluesky internally uses for others to implement their own social media platforms with total compatibiliy, avoiding the users content vendor lock-in, and allowing them to migrate their data to the server of their choice. #footnote[A nice analogous for quick understanding is to compare the platform-content such as a web-domain and the physical server: you can swap the provider as the domain is yours, and the infrastructure to run it is open-source. @abramov2025opensocial] for the user, as well as an unprecedented transparency for network science researchers. As ATProto is open, the events created by the users are publicly availabe and collectable for anyone who's listening to the proper port (see @apx-data for more info). For the first time, researchers can access raw, unaggregated data detailing who follows whom, who posts what, and who interacts with which content, entirely free from the filtering mechanisms of a platform's internal analytics team. This work builds directly on top of that opportunity.

== Information Diffusion

Information diffusion is the study of how discrete pieces of content propagate through a network infrastructure over time. Within a modern microblogging environment, the mechanics of spread are governed by interactions on three primary axes:
- *Platform Affordances:* The architectural features of the system—user interfaces, chronological feeds, notification delivery, recommendation algorithms—that determine the structural pathways through which content can reach a user. A reverse-chronological timeline is not functionally equivalent to an algorithmic feed; a platform implementing an explicit repost mechanism creates distinct cascading trees compared to one without it. These are not neutral design choices; they actively shape what spreads and what dies.
- *User Dynamics:* The explicit behavior patterns of individuals: when they log in, how long they scroll, how frequently they create posts, and what actions they take when presented with content. Human activity in social media is highly bursty and intermittent @barabási2005bursts and these rhythms create narrow temporal windows of opportunity for content to be either prioritized or buried. 
- *User-Content Interaction:* The semantic alignment between a post's message and a user's latent preferences, rooted in homophilic dynamics. A user who likes sports cars will predictably engage more with content about sports cars. This is, intuitively, the most powerful driver of engagement—but it is also the most complex to model, as it requires representing both the semantic footprint of posts and the high-dimensional preferences of users in a computationally tractable way.

This work will focus on the Plaftorm Affordances ---what the model has--- and the User Dynamics ---how can we characterize a user behaviour--- as the User-Content interaction falls out of scope due to difficulty and time constraints.

When a piece of content traverses a network and users keep propagating it, it creates a cascade. The cascade is a graph, shaped as a tree, of users that have interacted with that post.Cascades are the main object of interest of this work, as they allow to trace the full path of a piece of content has followed, being able to deduce from it important characteristics of how did this post impact both the network and the users that have interacted with it.  

== Objectives

The aim of this work is to generate synthetic cascades resembling the ones extracted from empirical Bluesky Firehose data. To achieve that, a model to represent a microblogging social network platform minimal viable features will be introduced (a Continuous-Time Independent Cascade model, with a LIFO-based timeline and an activity-driven user behaviour) with the following scope limitations to make the work fit in a master thesis: homogeneous posts and user interaction with them and no new users while the simulation runs.

To achive this, the thesis can be seen as three different parts:
1. *Evaluating the model*: as the complexity of multiple users is extremly high, it needs to be simulated. The simulation must be designed, implemented and evaluated to ensure correct and scalable functioning.
2. *Informing the simulation*: from empirical Bluesky data, we must extract the behaviours of the users to use the simulation with adequate data. The simulation will also need a network topology to ran over, which will be extracted from empirical Bluesky data as well.
3. *Objective Quantites*: to evaluate the simulation we need both quantities to replicate and quantities to observe. The quantities to replicate allows to judge the accuracy of the simulation, and the quantites to reproduce are the characteristics the simulation is built to study, but to be able to compare them they must be found in the first place, extracted again from empirical data.
4. *Execution, Comparison and Evaluation*: compare the emprical with the synthetic cascades, asses if there are any rellevant differences and if any, explicitly mark the model limitaitons on why the cascades differ.

== Hypotheses & Research Questions
<sec-hypotheses>

A microblogging platform in full is intractable to reproduce one-to-one: dozens of interactions, features and ranking mechanisms act at once. This work purposely does not attempt that. It asks instead whether the _core_ of the process can be built, calibrated and verified on its own, as a foundation on which the rest can later be assembled. Formalized as a hypothesis, this has the form:

*Hypothesis.* A model built from a small set of characteristic features of a microblogging platform ---an asymmetric follow graph, a reverse-chronological timeline and repost amplification, driven by the users' own activity rhythms--- calibrated end-to-end from openly available data and executed at network scale, is sufficient to reproduce the underlying mechanics of information diffusion and generate post cascades similar to empirical data? Even under agressive simplification, will set of features chosen be able to resemble empirical data?

We will explore the veracity of the hypothesis with the following research questions, which will be promptly answered in the Conclusions @sec-conclusions.

*RQ1 --- Measurability.* Can the platform's user dynamics (user sessions, posts created, action rates) and a representative follower topology be recovered from openly available ATProto data, at the per-user resolution the model requires? Can complex evaulation metrics (such as Structural Virality) be computed from the empirical data?

*RQ2 --- Executability.* Can a discrete-event implementation of the model run at a large enough scale ---up to $10^6$ nodes--- with feasible time and memory, and reach a stationary regime independent of the initial condition?

*RQ3 --- Core validity.* Does the calibrated core reproduce the shape class of the empirical cascades ---though not their magnitudes--- with the non-trivial-cascade rate about half the empirical one? Can it reproduce evaluation metrics successfully?

*RQ4 --- Boundary.* Are the model limitations and missing features be a plausible explanation of the missing results? Is the deviation attributable, mechanism by mechanism, to what the model does not yet contain?

*RQ5 --- Specification of the missing mechanism.* Can the measured residual be translated into a minimal, implementation-independent specification of what the model lacks ---the necessary properties the missing mechanism must have, rather than one particular way of building it?

RQ1--RQ2 establish that the construction is possible; RQ3 verifies the core; RQ4 measures the boundary; RQ5 turns that boundary into a specification of the next layer. Together they are what makes this a first step rather than a final answer.

== Thesis Structure

The body of the report carries the argument; derivations, engineering detail, negative results and discarded alternatives are relegated to the appendices, which are cited at the point where they matter. The route the reader will follow is the one below.

*Section 2 — State of the Art:* Outlines the theoretical background of Social Network Analysis (topologies, scale-free structure, small-world effects and homophily), continuous-time cascade dynamics and the Activity-Driven network model, the architectural mechanics of the Bluesky ecosystem, and the history of social-network simulation across Agent-Based, Generative-Agent and Discrete-Event paradigms.

*Section 3 — Problem Formulation:* Formalizes the unified mathematical model of the microblogging platform using time-varying graph principles. Introduces the explicit delay parameters, the session mechanics, the CTIC propagation kernel, the effective transmission rate and the final model expression. The two design decisions that are easiest to get wrong—why a propagation delay is necessary to avoid content teleportation, and why stale events need an explicit invalidation rule—are worked through with minimal examples in @apx-examples, while the mechanics that were considered and left out of this baseline (quoting, notifications, replies) are documented in @apx-mechanics.

*Section 4 — Methodology:* Justifies the selection of the Discrete-Event Simulation paradigm over Agent-Based Modeling, establishes the core engine rules, and defines the evaluation metrics (repost distribution, cascade size and shape, Structural Virality). The supporting methodological machinery lives in @apx-method: the random-number generators written for the engine, the distribution-fitting and goodness-of-fit battery behind the calibration---including the Pareto family and Vuong's test---and the sessionization procedures.

*Section 5 — Design:* Details the algorithmic decisions that enable the simulation to execute effectively at scale: event types, the event queue, propagation delays, offline-event handling, and structural entities. @apx-impl covers the concrete realization: Data-Oriented Design memory layouts, Compressed Sparse Row (CSR) topology storage, power-of-two indexing, the buffered binary I/O trace pipeline and the trace validator, together with the four incremental engine versions that led to the final release. The code itself, its repositories and build system are catalogued in @apx-code.

*Section 6 — Bluesky Data Analysis:* Characterizes the empirical firehose data that the model is calibrated against and evaluated on: the event stream, the repost power law, cascade shape, Structural Virality and follower-topology extraction. @apx-data describes the raw dataset and the `via_uri` field that makes repost-cascade reconstruction possible, and @apx-topology documents the ingestion pipeline and Forest Fire sampling used to obtain the simulation-ready follower graphs.

*Section 7 — Calibration:* Maps the analytical findings into the calibrated parameter sets used to configure the final evaluation runs: session construction, session-duration and inter-session laws, inter-post creation times, offsets, inter-action times, the user policy $pi$, warm-up and the stability regime. The detailed fits, their failures and the alternatives that were discarded are reported in @apx-sessions for sessions, @apx-creation for post creation, and @apx-stability-plots for the initial-condition convergence of the steady-state experiment.

*Section 8 — Results:* Analyzes the simulation performance and emergent behaviour: warm-up dynamics, steady-state convergence, computational scalability, the reproduced power law, cascade metrics and Structural Virality, followed by the comparison against empirical Bluesky data and the localization of the missing tail. The random-timeline ablation that isolates the contribution of the LIFO timeline is reported in full in @apx-random-timeline; the reproducibility pipeline that turns raw traces into the analyzed datasets is described in @apx-pipeline; and the machine on which every run was executed is specified in @apx-hardware.

*Section 9 — Conclusions:* Answers the research questions stated above, separating what the baseline reproduces from what it demonstrably cannot, and states the boundary of the model as a result rather than a caveat.

*Section 10 — Future Work:* Summarizes the operational achievements of the baseline and details the expansion pathways, from performance and metric improvements to the content-aware layer. The concrete mathematical roadmap for that layer---embedding similarity spaces, heterogeneous policies and Large Language Model generative agents, with their computational trade-offs---is developed in @apx-content.

The remaining appendices support the work as a whole: @apx-ai declares the generative-AI usage required by the university, and @apx-code documents the delivered repositories and how to build and run them, so that every result in the body can be reproduced.
