#import "utils.typ": *

Information diffusion in social networks is an extremely challenging problem, in three very well defined aspects. First, the modelling and replication of human behaviour requires a high amount of quality and very specific data as well as sophisticated approaches in the reproducibility: the task is to describe and replicate a social behaviour, which is not easy. Secondly, the description is not of _one_ individual, but of a high quantity of them to generate the dynamics linking the collective and the individuals. Lastly, a great quantity of interactions and phenomena happen on microblogging social networks: user-to-user interaction, user-to-post interactions, bios, different feeds, replies and quotes, notifications... the system to describe is very extensive if the intended purpose is to do a one-to-one reproducibility. Let's address how this work has managed these three main roadblocks.

Regarding data acquisition, this project is only possible thanks to the ATProto implementation and the existence of Bluesky, as it has made available exact data of events that allow to measure certain parts of human behaviour on the social network ---such as which content is reposted @sec-data-firehose, obtaining of the network topology @sec-data-topology, and reconstruction of the structural virality with the `via` field @anx-data-via --- and allowed to use methods to obtain non collected or not publicly available information ---such as sessions definitions @sec-method-session and its appendix @apx-sessions or posts per sessions @sec-cal-interaction. Despite Bluesky openness, this does not make the current available data optimal, in fact it is quite far away from it. If real session data from Bluesky and other networks were to be obtained, far more sophisticated analyses ---with probably more accurate results--- could be performed (see @sec-future).

Regarding the scalability, strong efforts to make the simulation performant have been made in this work: from the programming language election to the implementation itself @apx-impl and simulation paradigm (Discrete-Event Simulation @sec-method-des) together with its design @sec-design . The simulation is capable of running a 12 hours 1 million users run in 18 real life minutes @sec-res-scalability in a not dedicated server environment @apx-hardware which is more than enough to be representative of the scalability, as well as allowing pretty fast iteration on the simulation itself and obtaining results.

Regarding system intrinsic complexity, some scope adjustments were needed to fit inside the scope of a master thesis work and managing all the complexity. First, a subset of features from Bluesky was taken into account to be modeled as the minimum skeleton of what a microblogging social network is (see @sec-sota-description and @sec-model), with three big feature omissions such as reply, quoting and notifications @apx-mechanics in order to fit the scope. The subset of features can be described at high level as three possible user-post actions (repost, like or ignore) with a reverse-chonological timeline, excluding recomendation algorithms and impossibility of users interacting between each other; together with a Continuous-Time Independent Cascade with Activity driven nodes, this is the exact model presented and studied in this project.

Once the object to model was closed, some more simplifications were needed to not drown into the calibration complexity and implementation of the model: post homogeneity (treating posts as content-agnostic pods that propagate through the network) which ultimately implies user policy homogeneity over defined actions and a static network topology (no new users would join the simulation while it's active).

This work does not hide that, under all these simplifying assumptions, the implemented simulation can't be comparable to a fully-featured microblogging social network such as Bluesky. Despite the fact, the system manages to replicate accurately the bulk of virality and the reposts power-law distributions ---the two metrics decided to evaluate the simulation upon (@sec-method-des-metrics), and fails to reproduce the extreme behaviour of the characteristic long tail of social networks @sec-finding-missing-tail. This has been found to have specific root causes proved with some subexperiments of their own.

The non-realization of the extreme long tail reposts and virality is equivalent to saying the simulations are not as deep as their empirical data counterpart. Under the content agnostic assumption, it can be seen that a cascade is a Galton-Watson process with a subcritical reproduction number $R_0$ equal for all the cascades, making their aggregation distribution not generate a heavy tail. If we supposed every cascade had a different $R_0$ by making them draw from a distribution $F$ representing post content and the support of $F$ gets arbitrarily close to $1$, the distribution generated for the mixed model will indeed contain a heavy tail. Therefore, adding content-aware posts would create the diversity for posts to generate far deeper cascades. Furthermore, the Future Work (@sec-future) theoretically describes how to implement content-aware posts by the usage of embeddings and how to make the action policy $pi$ heterogeneous and content aware.  

The second problem is that the maximum degree of the cascades is far smaller (5 times) than the ones of empirical data, which means the synthetic cascades are shallower than the empirical data cascades. The main cause of this is the attention war in the reverse-chronological timeline due to the extreme competition there is for every post in the simulation. Posts get buried in user timelines due to the quantity of posts that users generate (see @sec-missing-width).
#comment[
  The problem here is that our simulation has all the users as the 20% more active, as it is probably tied with the degree of the simulation and we did not take that into account as the analysis would have needed far more data. Also, we are missing with respect to the cascades the "likes" (a post can end up in your timeline because another user liked it ) and the quoted, so we are using one of three mechanisms compared to the empirical cascades.
]  

In conclusion, this work successfully completed the task it initially proposed, which is to study information diffusion in microblogging social networks by accurately identifying the subset of indispensable features of Bluesky, designing a mathematical model that was able to represent them, introducing restrictions to reduce and atomize complexity and scope, designing a discrete-event simulation to evaluate the model as well as distinguishing the inputs, and implementing a high performance engine in a systems level programming language to achieve scalability.
In parallel, it analyzed empirical data to inform the user behaviour in the simulation and calibrate all the parameters needed by the simulation to run, as well as extracting and sampling a subset of Bluesky follower topology which conserves the social network properties and, lastly, obtained ground truth from the empirical data to compare the synthetic cascades in the reposts power-law and structural virality.
With the combination of both the simulation and empirical data, results can be obtained and evaluated. Those are satisfactory as, despite the feature difference between the modeled simulation and Bluesky, the bulk of the distributions matches, confirming the underlying assumptions are correct. For the not matching assumptions (depth and width of the cascades), explanations are provided that inform why the work done until now is a solid basis to expand upon it with content-aware posts, more features and deeper analysis of the topology, making this work a solid first step into an accurate cascade synthetic simulator, allowing the study of hotter topics such as echo chambers, misinformation and democratic welfare in online platforms.




