#import "utils.typ": *

Information diffusion in social networks is an extremely challenging problem, in three very well defined aspects. First, the modelling and replication of human behaviour requires a high amount of quality and very specific data as well as sophisticated approaches in the reproducibility: the task is to describe and replicate a social behaviour, which is not easy. Secondly, the description is not of _one_ individual, but of a high quantity of them to generate the dynamics linking the collective and the individuals. Lastly, a great quantity of interactions and phenomena happen on microblogging social networks: user-to-user interaction, user-to-post interactions, bios, different feeds, replies and quotes, notifications... the system to describe is very extensive if the intended purpose is to do a one-to-one reproducibility. Let's address how this work has managed these three main roadblocks.

Regarding data acquisition, this project is only possible thanks to the ATProto implementation and the existence of Bluesky, as it has made available exact data of events that allow to measure certain parts of human behaviour on the social network ---such as which content is reposted (see @sec-data-firehose), obtaining of the network topology (see @sec-data-topology), and reconstruction of the structural virality with the `via` field (see @anx-data-via) --- and allowed to use methods to obtain non collected or not publicly available information ---such as sessions definitions (see @sec-method-session) and its appendix (see @apx-sessions) or posts per sessions (see @sec-cal-interaction). Despite Bluesky openness, this does not make the current available data optimal, in fact it is quite far away from it. If real session data from Bluesky and other networks were to be obtained, far more sophisticated analyses ---with probably more accurate results--- could be performed (see @sec-future).

Regarding the scalability, strong efforts to make the simulation performant have been made in this work: from the programming language election to the implementation itself (see @apx-impl) and simulation paradigm (Discrete-Event Simulation, see @sec-method-des) together with its design (see @sec-design). The simulation is capable of running a 12 hours 1 million users run in 18 real life minutes (see @sec-res-scalability) in a not dedicated server environment (see @apx-hardware) which is more than enough to be representative of the scalability, as well as allowing pretty fast iteration on the simulation itself and obtaining results.

Regarding system intrinsic complexity, some scope adjustments were needed to fit inside the scope of a master thesis work and managing all the complexity. First, a subset of features from Bluesky was taken into account to be modeled as the minimum skeleton of what a microblogging social network is (see @sec-sota-description and @sec-model), with three big feature omissions such as reply, quoting and notifications (see @apx-mechanics) in order to fit the scope. The subset of features can be described at high level as three possible user-post actions (repost, like or ignore) with a reverse-chonological timeline, excluding recomendation algorithms and impossibility of users interacting between each other; together with a Continuous-Time Independent Cascade with Activity driven nodes, this is the exact model presented and studied in this project.

Once the object to model was closed, some more simplifications were needed to not drown into the calibration complexity and implementation of the model: post homogeneity (treating posts as content-agnostic pods that propagate through the network) which ultimately implies user policy homogeneity over defined actions and a static network topology (no new users would join the simulation while it's active).

This work does not hide that, under all these simplifying assumptions, the implemented simulation can't be comparable to a fully-featured microblogging social network such as Bluesky. Despite the fact, the system manages to replicate accurately the bulk of virality and the reposts power-law distributions ---the two metrics decided to evaluate the simulation upon (see @sec-method-des-metrics), and fails to reproduce the extreme behaviour of the characteristic long tail of social networks (see @sec-finding-missing-tail). This has been found to have specific root causes proved with some subexperiments of their own.

The non-realization of the extreme long tail reposts and virality is equivalent to saying the simulations are not as deep as their empirical data counterpart. Under the content agnostic assumption, it can be seen that a cascade is a Galton-Watson process with a subcritical reproduction number $R_0$ equal for all the cascades, making their aggregation distribution not generate a heavy tail. If we supposed every cascade had a different $R_0$ by making them draw from a distribution $F$ representing post content and the support of $F$ gets arbitrarily close to $1$, the distribution generated for the mixed model will indeed contain a heavy tail. Therefore, adding content-aware posts would create the diversity for posts to generate far deeper cascades. Furthermore, the Future Work (see @sec-future) theoretically describes how to implement content-aware posts by the usage of embeddings and how to make the action policy $pi$ heterogeneous and content aware.  


The second problem is the width of the cascades: the maximum out-degree is about five times smaller than in the empirical data ($1,599$ against $7,768$). Width is decided at the first hop ---$EE("out-degree") = d_"followers" dot pi_"repost"$--- and the simulation shows that reach barely keeps up with degree: across four decades of follower count the typical cascade grows only from $1.0$ to $2.8$, with the whole tail concentrated in the single largest hub and the per-follower conversion collapsing as degree grows. That collapse is the missing width.

The obvious suspect was the reverse-chronological ordering, which buries posts under newer ones. Randomising the timeline drain reallocates *which* cascades grow but does not widen them ---aggregate metrics are flat and only the single luckiest cascades improve--- so ordering is second-order. The binding cap is the impression budget and the conversion rate: a session reads a bounded number of posts shared across every account it follows, so impressions saturate far below the follower count, and because posts carry no content every post shares the same repost probability, so none can convert above baseline. Lifting the width therefore requires impressions *beyond* the follower graph and content-aware, post-level conversion ---a recommender--- rather than a better queue order.

In conclusion, this work set out to test whether the irreducible mechanics of a microblogging platform are sufficient to reproduce the underlying mechanics of information diffusion, and the hypothesis in @sec-hypotheses holds on both sides. The construction succeeded end to end: the user dynamics and a representative follower topology were recovered from openly available ATProto data at per-user resolution (RQ1), and the discrete-event engine runs the model at the scale of the real network --- up to one million users --- in feasible time and memory while reaching a stationary regime (RQ2). The calibrated core then reproduces the qualitative shape of the empirical cascades --- the same tiny, shallow, broadcast-dominated regime, with matching bulk statistics and a non-trivial-cascade rate that is the one quantity off by about a factor of two (RQ3) --- so that agreement confirms the modelled mechanisms are the load-bearing part of the phenomenon.

Where the model departs from reality, it does so for reasons that are identified rather than residual (RQ4): cascade depth is bounded by the subcritical reproduction number inherited from content-agnostic behaviour, and cascade width by in-network-only impressions and a uniform conversion rate. Together those findings are a specification of what the model lacks (RQ5) --- the necessary properties of the missing mechanism, independent of how it is implemented. That is what makes this a verified baseline rather than a finished model: the parts it does not explain are named, and named in the place where the next mechanism must enter. As such, it is a solid first step into an accurate synthetic cascade simulator, to be extended with content-aware posts, more features and a deeper analysis of the topology, enabling the study of hotter topics such as echo chambers, misinformation and democratic welfare in online platforms.




