
Information diffusion in social networks is an extremely challenging problem. This difficulty stems not only due to a scale problem ---enormous amount of data, and the need of big sample sizes to properly extrapolate results--- but the nature of the problem in itself: capture human behaviour in a complex system.

To make the intrinsic complexity in a system like the one this project is about manageable, it is imperative the use of simplifications and assumptions to be able to tackle the problem in the first place.

The primary objective of this project was to model information diffusion within a microblogging network to observe how cascades unfold and locate the bounds of content virality, as well as analyzing content lifetimes. Managing this complexity required three major simplifications: post homogeneity (treating posts as content-agnostic commodities), a temporally static network topology (omitting edge growth or structural evolution over time), and user policy homogeneity. While these assumptions strip away significant real-world nuances, the simulation successfully yielded highly coherent and behaviorally relevant results. This successfully highlights that the assumptions and simplifications needed to manage complexity into a manageable problem are not a limitation, but a tool that allowed us quantify the importance of the isolated factors in the content diffusion role. 

To evaluate this simplifies dynamics, a Continuous-Time Independent Cascade model with a Queue-based delay and an Activity-driven network has been prosed, trying to mimic both user behaviour (the content must be propagated in sessions) and the timeline checking users (the posts are enqueued and served to the user with a specific criteria) to be as accurate as possible. This system is impossible to describe analytically, therefore a method of evaluation was needed. Consequently, this work presents a high performance Discrete-Event simulation engine to evaluate the descibed model. 

To evaluate the model, this work has reconstructed two years of Bluesky Firehose data to provide several samplings of the network topologies, as well as analyzed 6 days of full event information to calibrate the simulation as close to the original Bluesky data as possible. With around 1700 evaluations, a significant amount of data has been obtained for the results to be analyzed and significant about model corecntess and behaviour. The large amount of replications has been possible due to the implementation growing in linear time with the input, making the evaluations and result replications of big topologies not only possible, but feasible in short time spans as this project has been.

Utilizing empirical datasets sampled from the real-world Bluesky social network, the simulation traces analysis confirmed that the engine achieves robust, steady-state equilibrium across massive populations. The empirical validation highlighted areas of strong performance, such as capturing structural power laws and multi-generational temporal inheritance. At the same time, it exposed critical design boundaries, particularly regarding timeline starvation and parameter sensitivity under strict post homogeneity, which it is believed can be addressed with some amount of work without chaning the main dynamics of the model. These limitations do not detract from the model, but rather provide a strictly validated, high-performance computational foundation for future work into content-aware, heterogenous social simulation.

In conclusion, this work serves as a foundational stepping stone toward addressing deeply relevant issues in modern digital society. With this simulation acting as a validated structural baseline, our findings provide a direct roadmap for model improvement. Specifically, by relaxing the post homogeneity assumption and integrating machine learning embeddings, future iterations can evolve past simple data propagation. Introducing homophilic principles and content-aware mechanics will allow the model to simulate real-world echo chambers, shifting the focus of this research from explaining how information diffuses to actively analyzing the quality of civic discourse itself.
