#import "utils.typ": todo, comment, flex-caption

This chapter describes the Bluesky Firehose dataset —-its structure, content, and the statistical properties of the content it carries. The post lifetime dynamics and structural virality are characterised here as properties of the platform itself, and described accordingly to Methodology @sec-method-des-metrics. The translation of these findings into simulation calibration parameters is deferred to @sec-calibration. The technology stack used throughout the data pipeline is documented in @apx-software-stack.

== Firehose Data Description
<sec-data-firehose>

The Bluesky Firehose is a continuous stream of all public AT Protocol events emitted by the network. For this study, a 6-day snapshot (April 11--17, 2026) was ingested into a StarRocks columnar database. The raw data is organised into two tables in the `bsky` schema, summarised in @tbl-firehose-schema.

#figure(
  table(
    columns: 4,
    align: (left, center, center, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Table*], [*Rows*], [*Unique DIDs*], [*Content*],
    table.hline(stroke: 0.5pt),
    [`bsky.posts`], [$28.1 times 10^6$], [$1.45 times 10^6$], [Normalised post content (text, language, reply chains)],
    [`bsky.records`], [$212.5 times 10^6$], [$2.84 times 10^6$], [All AT Protocol record events (likes, reposts, follows, blocks, etc.)],
    table.hline(stroke: 0.8pt),
  ),
    caption: flex-caption(
      [Firehose data schema: `bsky.posts` and `bsky.records` tables.],
      [Firehose data schema: `bsky.posts` and `bsky.records` tables. `posts` contains $28.1 times 10^6$ normalised post records; `records` contains $212.5 times 10^6$ AT Protocol events across 16 lexicon collections. Generated by the Go producer-consumer ingestion pipeline.],
    ),
    alt: "Firehose data schema summary."
  
) <tbl-firehose-schema>

=== The `bsky.posts` Table

The `posts` table is a normalised extract of `app.bsky.feed.post` records. It contains $28.1 times 10^6$ rows with columns `did`, `rkey`, `time_us`, `created_at`, `post_text`, `lang`, and reply-chain fields (`reply_root_uri`, `reply_parent_uri`).

- *Top-level posts* (`reply_root_uri IS NULL`): $15.3 times 10^6$ (54.4%) — original content that starts a new thread or stands alone.
- *Replies* (`reply_root_uri IS NOT NULL`): $12.8 times 10^6$ (45.6%) — responses within existing threads.

Language coverage is dominated by English (60.8%), followed by Japanese (10.6%), Portuguese (2.8%), German (2.8%), and Spanish (2.6%). Approximately 11.7% of posts have no language tag.

Due to an unfortunate processing event, quote-posts are currently absent from `bsky.posts` because the dump pipeline did not extract the `record.embed` field. A spot-check of the raw firehose shows ~5.6% of posts are quote-posts. These are misclassified as plain posts or replies. This is a known limitation of the database dump, not of the analysis.

=== The `bsky.records` Table

The `records` table is a comprehensive dump of almost all the AT Protocol record events. It contains $212.5 times 10^6$ rows, with operations dominated by `create` (96.9%), followed by `delete` (2.7%) and `update` (0.4%).

The three dominant record types account for 97.3% of all records, as can be seen in @tbl-records-collections.

#figure(
  table(
    columns: 4,
    align: (left, right, right, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Collection*], [*Count*], [*%*], [*Description*],
    table.hline(stroke: 0.5pt),
    [`app.bsky.feed.like`], [$161.7 times 10^6$], [76.1%], [Likes on posts],
    [`app.bsky.feed.repost`], [$26.4 times 10^6$], [12.4%], [Reposts (retweets)],
    [`app.bsky.graph.follow`], [$18.8 times 10^6$], [8.8%], [Follow relationships],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [The three dominant record types in `bsky.records`.],
    [The three dominant record types in `bsky.records`. Likes alone constitute over three-quarters of all firehose events.],
  )
) <tbl-records-collections>

Remaining types include blocks ($1.7 times 10^6$, 0.8%), thread reply controls, profile updates, list memberships, and other moderation records — 16 lexicon collections in total. The `records` schema includes `subject_uri`, `subject_did`, and a full `record_json` payload, enabling reconstruction of the target of every like, repost, follow, and block. A full description of the database table schema can be found in @apx-database.

Between the two different tables, there are a total of $3.09 times 10^6$ DIDs (direct ID) which are distinct users in all data set. Approximately 1.63 million users (52.8%) appear in `records` but never authored a post, therefore will be excluded from certain metrics as not active enough.

A systematic EDA was conducted to understand the distribution of user activity and identify which users drive the inter-event gap distribution, that is, the distribution of time that happens between actions. This magnitude is fundamental, as is what is going to drive the methodology of how to define how a session in should be found in the data (see Calibration @sec-cal-sessions). 

=== Event-Count distribution

The number of events per user follows a heavy-tailed power-law distribution. The median user has 8 events over the 8-day window; $P_75$ is 39 events; $P_99$ reaches 1,185 events. The top 1% produce 148 more events than the median user.

#figure(
  image("images/data/6-1_events_powerlaw.png", width: 100%),
  caption: flex-caption(
    [Complementary CDF of events per user (log-log).],
    [Complementary CDF of events per user (log-log). A power-law fit (Clauset et al. MLE with KS-based $x_min$ selection) yields $alpha approx 1.56$, $x_min = 8$. The straight-line decay in the tail confirms power-law behaviour.],
  )
) <fig-events-powerlaw>

A power-law fit via MLE with KS-based $x_min$ estimation @clauset2009powerlaw yields $alpha approx 1.56$, $x_min = 8$ events. Since the heavy tail begins at 8 events, users with fewer than 8 events — half of the population — are considered tourists whose activity is too sparse to produce meaningful session statistics.

The next step, once know the power-law of the events per user per 8 days, is to classify the users according to event counts. The @tbl-coverage shows the bins used to classify the users by total event count and asks: which stratum holds the most amount of events and gaps between them?

#figure(
  table(
    columns: 5,
    align: (left, center, center, center, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Events*], [*Users (%)*], [*Events (%)*], [*Gaps (%)*], [*Role*],
    table.hline(stroke: 0.5pt),
    [1],          [22.6],  [0.7],   [0.0],  [Irrelevant],
    [2–5],        [30.1],  [3.0],   [2.1],  [Negligible],
    [6–25],       [27.7],  [11.1],  [10.6], [Meaningful],
    [26–100],     [13.4],  [22.0],  [22.3], [Meaningful],
    [101–500],    [5.5],   [36.3],  [37.4], [Dominant],
    [501+],       [0.8],   [26.8],  [27.7], [Bot-heavy],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Coverage analysis.],
    [Coverage analysis: the 101–500 event bucket (5.5% of users) supplies 37.4% of all inter-event gaps — the stratum that objectively drives any gap-based analysis.],
  )
) <tbl-coverage>

#figure(
  image("images/data/6-1_coverage.png", width: 85%),
  caption: flex-caption(
    [Share of inter-arrival gaps contributed by each user stratum.],
    [Share of inter-arrival gaps contributed by each user stratum. The 101–500 bucket (5.5% of users) dominates with 37.4% of gaps.],
  )
) <fig-coverage>

The tourist majority ($<=5$ events, 52.7% of users) is barely visible in the gap distribution. The 501+ bucket adds another 27.7% of gaps, but users in this range generate over 62 events per day on average — a rate suspicious of automated or scheduled accounts. Together, just 6.3% of users drive 65.1% of the gap distribution.

On the basis of this EDA, two event tables were created in `data`, both time-windowed to the 8-day snapshot (April 11--18, 2026):

- *`data.all_events`* ($approx 1.6 times 10^6$ users, $>= 8$ events): all 6 major event types (likes, reposts, follows, blocks, top-level posts, replies). The $>= 8$ cutoff is the power-law $x_min$ from the all-events distribution ($alpha = 1.56$). This table feeds the browsing-oriented session pipeline.
- *`data.engaged_events`* ($approx 2.4 times 10^6$ users, $>= 4$ events): 5 engaged event types — reposts, follows, blocks, posts, replies — *without likes*. The $>= 4$ cutoff is the power-law $x_min$ for engaged events ($alpha = 1.67$). This table feeds the content-creation-oriented session pipeline and the inter-post gap analysis.

Both tables follow the schema `(did, time_us, event_type)`, with 32 hash-distributed buckets for parallel query execution. See @apx-database for the full database specification.

== Post Lifetime Analysis
<sec-data-lifetime>

Whereas session analysis is needed for the calibration, we will compute the quantities of interest of the simulation, to compare them with the data real life simulation data. This section studies the lifetime of $15.3 times 10^6$ top-level posts in the firehose snapshot (posts with `reply_root_uri IS NULL`).

=== Data Preparation

Two tables were created to support the analysis:

- *`data.post_lifetime`* — one row per top-level post, precomputing the first and last timestamp of each engagement type (repost, like, reply) plus total counts ($15.3 times 10^6$ rows).
- *`data.post_engagement_events`* — individual event timeline for every post, with columns `(post_did, post_rkey, event_time_us, event_type, actor_did)`. Enables temporal decay and cascade analysis ($approx 140 times 10^6$ rows).

Only top-level posts are included; replies are thread participants rather than original content. Quote-posts are absent from the dump (see @sec-data-firehose).

=== Engagement Counts

A striking 50.7% of posts receive no engagement at all. Of engaged posts, likes are the most common (92.7%), followed by replies (35.4%) and reposts (33.1%). The Python script `eda/fit_powerlaw_counts.py` fits a discrete power-law via MLE with KS-based $x_min$ selection and compares against lognormal, Weibull, and exponential alternatives via Vuong's LLR test.

For each engagement type, the counts in the tail follow a discrete power-law (@tbl-powerlaw-counts). The power-law is strongly favoured over all alternatives: Vuong's $R$ values range from $+2,933$ (replies vs lognormal) to $+85,822$ (combined vs exponential), with $p < 0.001$ throughout.

#figure(
  table(
    columns: 6,
    align: (left, center, center, center, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Type*], [*$alpha$*], [*$x_min$*], [*$n_"tail"$*], [*KS*], [*$p$*],
    table.hline(stroke: 0.5pt),
    [Reposts], [2.21], [84], [30,610], [0.0145], [1.00],
    [Likes], [2.15], [127], [112,443], [0.0093], [1.00],
    [Replies], [2.26], [42], [9,206], [0.0273], [1.00],
    [Combined], [2.14], [152], [115,128], [0.0087], [1.00],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Discrete power-law fit on engagement counts.],
    [Discrete power-law fit on engagement counts. All four pass the bootstrap goodness-of-fit test ($p > 0.05$). $alpha approx 2.15$ lies in the finite-mean, infinite-variance regime — engagement is extremely concentrated on very few posts.],
  )
) <tbl-powerlaw-counts>

So, its safe to say that (and consistently with the literature) post lifetimes do follow a power-law.

#figure(
  image("images/data/6-3_engagement_counts_ccdf.png", width: 90%),
  caption: flex-caption(
    [Complementary CDF of engagement counts.],
    [Complementary CDF of engagement counts for reposts, likes, and replies. All three decay as straight lines in log-log space — the hallmark of a power-law. Generated by `fit_powerlaw_counts.py`.],
  )
) <fig-powerlaw-counts>

=== Lifetime Distribution

*Question:* how long does a post stay alive? Lifetime is measured as $t_"last" - t_"created"$ for the $7.5 times 10^6$ posts that receive any engagement with positive lifetime.

The second question we have to ask about the data is the time a post stays alive. Lifetime of a post is defined as $t_"last" - t_"created"$ for the $7.5 times 10^6$ posts that recieve any engagement with positive lifetime.

The @tbl-lifetimes-fit shows the result of fitting four continuous distributions over the posts lifetimes. The lifetime exhibits a two-component structure: the body (lifetimes $< 15.6$ h, $approx 75$% of engaged posts) is best fit by a Weibull with shape $k = 0.53$; the tail ($> 15.6$ h, $approx 25$% of engaged posts) follows a Pareto with $alpha = 2.16$. The median lifetime is 3.8 h, but $P_{99}$ reaches 133 h (5.6 days).

#figure(
  table(
    columns: 4,
    align: (center, left, center, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Rank*], [*Distribution*], [*Log-likelihood*], [*Parameters*],
    table.hline(stroke: 0.5pt),
    [1], [Pareto (tail)], [$-23.8 times 10^6$], [$alpha = 2.16$, $x_min = 15.6$ h],
    [2], [Weibull], [$-84.7 times 10^6$], [shape $= 0.53$, scale $= 9.4$ h],
    [3], [Lognormal], [$-85.3 times 10^6$], [$sigma = 2.61$, $mu = 9.00$],
    [4], [Exponential], [$-88.8 times 10^6$], [scale $= 14.2$ h],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Distribution fit on post lifetimes.],
    [Distribution fit on post lifetimes. Pareto is best for the tail ($> 15.6$ h). Weibull (shape 0.53) best describes the body. Exponential is a poor fit — lifetimes are not memoryless.],
  )
) <tbl-lifetimes-fit>

#figure(
  image("images/data/6-3_lifetimes_ccdf.png", width: 90%),
  caption: flex-caption(
    [Combined post lifetime CCDF with distribution fit overlays.],
    [Combined post lifetime CCDF with Pareto, Weibull, and lognormal fit overlays. The Pareto fit captures the heavy tail; Weibull (shape 0.53) captures the body. Generated by `fit_powerlaw_lifetimes.py`.],
  )
) <fig-lifetimes-ccdf>

The Weibull shape $k = 0.53 < 1$ implies a decreasing hazard rate: a post is actually less likely to die the longer it has been alive, consistent with rich-get-richer dynamics. For simulation, the two-component model is the recommended calibration target.

=== Temporal Decay

Does a post, within its lifetime, within a post's lifetime, receive all it's engagement evenly in time or cluster early? The script `eda/temporal_decay.py` fits $N(t) prop t^beta$ — the cumulative number of events as a function of time since creation — per-post on a sample from four engagement-volume buckets.

#figure(
  table(
    columns: 5,
    align: (left, center, center, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Engagement bucket*], [*$n$*], [*Median $beta$*], [*Mean $beta$*], [*Std $beta$*],
    table.hline(stroke: 0.5pt),
    [20–99 events], [98], [0.49], [0.57], [0.27],
    [100–999], [99], [0.49], [0.53], [0.22],
    [1K–10K], [99], [0.52], [0.60], [0.25],
    [10K+], [99], [0.61], [0.64], [0.18],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Per-post temporal decay exponent $beta$ by engagement volume.],
    [Per-post temporal decay exponent $beta$ by engagement volume. All $beta$ values are well below 1 — engagement always decelerates. Higher-engagement posts spread events more evenly (higher $beta$), but no post in the sample showed linear or accelerating engagement.],
  )
) <tbl-temporal-decay>

All $beta$ values are well below 1: engagement always decelerates. However, $beta$ *increases with volume* — viral posts ($10K+$ events) spread engagement more evenly over time than typical posts. For simulation, sample $beta$ from $cal(N)(0.49, 0.27)$ for typical posts and $cal(N)(0.61, 0.18)$ for high-engagement posts.

The aggregate $beta$ (pooling all 3,000 posts then fitting) is 0.34 — substantially lower than any per-post median. This is a classic ecological fallacy: the aggregate curve is pulled down by the fact that most posts die quickly. The per-post distributions are the relevant calibration target.

=== Time-to-First Engagement

In general, how long until the first repost, like, or reply arrives after a post is created? @tbl-time-to-first shows the percentiles.

#figure(
  table(
    columns: 4,
    align: (left, center, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Percentile*], [*First repost*], [*First like*], [*First reply*],
    table.hline(stroke: 0.5pt),
    [$P_1$], [9.7 s], [6.4 s], [*0.9 s*],
    [$P_{50}$ (median)], [13.3 min], [5.6 min], [5.9 min],
    [$P_{95}$], [14.9 h], [8.0 h], [9.4 h],
    [$P_{99}$], [49.1 h], [30.0 h], [32.7 h],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Time-to-first-engagement percentiles.],
    [Time-to-first-engagement percentiles. Replies are the fastest ($P_1 = 0.9$ s, median 5.9 min); reposts are the slowest (median 13.3 min). The ordering reply < like < repost is consistent with the engagement ladder hypothesis.],
  )
) <tbl-time-to-first>

The ordering is consistent across all percentiles: replies arrive fastest, reposts slowest. At $P_1$, replies appear in under a second (likely automated or pre-coordinated interactions), while reposts take nearly 10 seconds.

#figure(
  image("images/data/6-3_time_to_first.png", width: 85%),
  caption: flex-caption(
    [Cumulative distribution of time-to-first-engagement.],
    [Cumulative distribution of time-to-first-engagement for reposts, likes, and replies (logarithmic time axis). Replies and likes are nearly indistinguishable at the median; reposts lag behind. Generated by `time_to_first.py`.],
  )
) <fig-time-to-first>

== Structural Virality
<sec-data-structural-virality>

Structural virality $nu(T)$ @goel2016structural captures the macro-level shape of the repost propagation tree — distinguishing between broadcast diffusion (one-to-many) and viral spread (person-to-person chains). This is the other objective quantity the simulation wants to study, and has already been defined in @sec-method-des-metrics.

=== Cascade Tree Reconstruction

Bluesky's AT Protocol records include a `via` field in repost events: when user C reposts, the `via.uri` tells us exactly which repost (by user B) they saw. This provides the true propagation path without needing to infer it from the follow graph. Two types of reposts are distinguished:

- *Direct reposts* (`via` is null, $17.6 times 10^6$, 69.3%): the user saw the original post. These anchor directly to the root.
- *Via reposts* (`via` has a value, $7.8 times 10^6$, 30.7%): the user saw someone else's repost. These attach as children of the referenced parent repost.

The implementation streams repost events sorted by `(subject_uri, time_us)`, groups them by original post, builds the tree using a `via_uri arrow.r node` hashmap, and computes $nu$ in $O(N)$ time. The pipeline consists of three steps: a SQL dump from StarRocks ($25.4 times 10^6$ rows, 5.2 GB TSV), a Go streaming computation (354 MB CSV, $4.4 times 10^6$ rows), and Python plotting. Total runtime is $approx 3$ minutes.

=== Virality Distribution

Of $15.3 times 10^6$ top-level posts, $4.41 times 10^6$ (28.9%) received at least one repost and therefore have a cascade tree with $nu > 0$. @tbl-virality-stats summarises the empirical distribution of the structural virality across $4.41 times 10^6$ different post cascades.

#figure(
  table(
    columns: 2,
    align: (left, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Statistic*], [*Value*],
    table.hline(stroke: 0.5pt),
    [$N$ (cascades)], [$4,407,830$],
    [$nu$ mean], [1.3505],
    [$nu$ median], [1.0000],
    [$nu$ std], [0.5736],
    [$nu$ max], [80.7410],
    [$nu$ $P_90$], [2.0331],
    [$nu$ $P_95$], [2.9765],
    [$nu$ $P_99$], [3.3733],
    [$nu$ $P_99.9$], [6.9299],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Structural virality summary statistics.],
    [Structural virality summary statistics for $4.41 times 10^6$ repost cascades. The median lies at the pure-broadcast boundary ($nu = 1$); 54.7% of cascades are exactly 1.0.],
  )
) <tbl-virality-stats>

54.7% of all cascades are pure broadcast ($nu = 1.0$). These are star-shaped trees where every reposter saw the original post directly — no chain of reposts. Figure @fig-virality-dist shows both the linear-scale histogram and the log-log distribution.

#figure(
  image("images/data/6-4_virality_distribution.png", width: 90%),
  caption: flex-caption(
    [Structural virality distribution.],
    [Structural virality distribution. Left: linear-scale histogram (peak at $nu = 1.0$). Right: log-log distribution showing fast decay above $nu approx 2$. Generated by `plot_virality.py`.],
  )
) <fig-virality-dist>

=== Virality vs Cascade Size

$nu$ grows sub-linearly with cascade size (@tbl-virality-by-size). The largest cascades ($1001+$ nodes) are $approx 15 times$ more viral on average than the smallest ($2$ nodes), despite being $approx 1,000 times$ larger. A cascade of $10,000$ nodes with $nu approx 5$ still looks more like a broad fan-out than a deep chain.

#figure(
  table(
    columns: 6,
    align: (left, center, center, center, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Size bucket*], [*$N$*], [*$nu$ mean*], [*$nu$ median*], [*$nu$ $P_90$*], [*$nu$ max*],
    table.hline(stroke: 0.5pt),
    [2], [$2,412,956$], [1.000], [1.000], [1.000], [1.000],
    [3], [$644,490$], [1.310], [1.333], [1.333], [1.333],
    [4–5], [$509,949$], [1.663], [1.500], [2.250], [4.500],
    [6–10], [$400,019$], [1.874], [1.667], [3.067], [7.067],
    [11–20], [$224,071$], [2.276], [2.067], [4.001], [14.357],
    [21–50], [$124,565$], [2.987], [2.790], [5.812], [28.003],
    [51–100], [$40,707$], [4.134], [3.698], [8.459], [44.606],
    [101–500], [$38,241$], [6.395], [4.971], [13.984], [73.243],
    [501–1000], [$5,221$], [9.718], [5.914], [22.586], [74.301],
    [1001+], [$7,611$], [14.738], [5.944], [31.157], [80.741],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Structural virality by cascade-size bucket.],
    [Structural virality by cascade-size bucket. $nu$ grows sub-linearly: the mean increases only $approx 15 times$ while cascade size grows $approx 1,000 times$.],
  )
) <tbl-virality-by-size>

#figure(
  image("images/data/6-4_virality_vs_size.png", width: 85%),
  caption: flex-caption(
    [Cascade size vs structural virality (hexbin).],
    [Cascade size vs structural virality (hexbin, log-scale x-axis). Black dots mark the mean $nu$ per size bucket. Values concentrate near $nu = 1.0$ for all sizes; the viral tail thins rapidly above $nu approx 3$.],
  )
) <fig-virality-vs-size>

=== Cascade Depth

73.4% of cascades have depth 1 — every reposter saw the original post directly. Even among viral cascades ($nu > 2$), the typical depth is modest (median 2, mean 3.1); high $nu$ values arise from the combination of non-trivial branching *and* chain structure. The deepest cascade (depth 235) corresponds to the post with $nu = 80.74$ and 12,720 nodes.

#figure(
  image("images/data/6-4_virality_depth.png", width: 85%),
  caption: flex-caption(
    [Cascade tree depth distribution.],
    [Cascade tree depth distribution. Left: linear-scale histogram (peak at depth 1). Right: log-log distribution. 73.4% of cascades have all reposters seeing the original post directly.],
  )
) <fig-virality-depth>

=== Tail Behaviour and Interpretation

The CCDF of $nu$ (@fig-virality-ccdf) decays faster than a power-law: above $nu approx 2$, the probability drops by roughly an order of magnitude per unit increase. At $nu = 10$, fewer than 1 in 10,000 cascades remain.

#figure(
  image("images/data/6-4_virality_ccdf.png", width: 75%),
  caption: flex-caption(
    [Complementary CDF of structural virality (log-log).],
    [Complementary CDF of structural virality (log-log). Dashed lines mark $P_{50}$, $P_{90}$, and $P_{99}$. Decay is faster than power-law — extreme virality is exponentially rare.],
  )
) <fig-virality-ccdf>

Bluesky is *predominantly broadcast*: 54.7% of cascades are pure one-to-many diffusion. For comparison, Goel et al. @goel2016structural found Twitter cascades also had median $nu approx 1.0$, but with a longer viral tail. Bluesky's distribution is more concentrated near $nu = 1$, consistent with a smaller, less densely-connected network. The three-regime classification (@tbl-virality-regimes) cleanly separates broadcast, mixed, and viral cascades.

#figure(
  table(
    columns: 4,
    align: (left, center, center, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Regime*], [*$nu$ range*], [*% of cascades*], [*Interpretation*],
    table.hline(stroke: 0.5pt),
    [Broadcast], [$nu = 1.0$], [54.7%], [One-to-many, no chain],
    [Mixed], [$1.0 < nu <= 3.0$], [42.7%], [Some chain structure, mostly shallow],
    [Viral], [$nu > 3.0$], [2.6%], [Multi-generational, true diffusion],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Three-regime classification of structural virality.],
    [Three-regime classification of structural virality. 97.4% of cascades are broadcast or mixed; only 2.6% reach genuinely viral diffusion.],
  )
) <tbl-virality-regimes>

For the agent-based simulation, the empirical $nu$ distribution provides a calibration target. A correctly calibrated simulation should reproduce: $approx 55%$ of cascades at $nu = 1.0$ (pure broadcast); median $nu approx 1.0$, mean $nu approx 1.35$; maximum $nu$ in the 50–100 range; and $nu$ growing sub-linearly with cascade size.

== Topology Obtention
<sec-data-topology>

The simulation requires a real social graph upon which information diffuses. The topology was extracted from the Bluesky firehose using `app.bsky.graph.follow` events, with `app.bsky.graph.block` events excluded (blocks serve a moderation role, not an information-propagation role).

=== Data Source

The dataset (distinct from the first described at the beginning of this chapter) spans 14 months (February 2025 to May 2026) with 88.4% calendar-day coverage. Two collection outages create known gaps: a 46-day window (July–August 2025) and an 8-day window (March–April 2026). Follows created and deleted entirely within a gap are lost; during-gap snapshots slightly overcount active edges since deletions within the gap are not recorded. For the end-of-window snapshot used in this work, these gaps have negligible impact — any edge active in April 2026 was almost certainly recorded.

The raw data was ingested from JSONL files organised as `YYYY-MM/DD/records_*.jsonl` under the firehose directory into a denormalised StarRocks `bsky_topology.graph_events` table via a Go producer-consumer pipeline (`topology/firehose/ingest/main.go`). The table contains $1.79 times 10^9$ rows spanning 16 lexicon collections, from which follow and block events are filtered. 

=== Graph Extraction (SCD Type 2)

#todo[Cite SCD archtecutres (explain what are they) and explain the type 2]
A three-phase DuckDB pipeline transforms the StarRocks event log into SCD2 Parquet files matching the `bluesky_db_specification.md` schema:

1. *Export* (Phase 1): DuckDB reads `graph_events` via the `mysql` extension in weekly chunks (70 Parquet files, 62 GB). Four parallel workers complete in ~12 minutes.
2. *SCD2 Transform* (Phase 2): A single DuckDB `GROUP BY uri` query collapses each AT Protocol record URI into one SCD2 row with `valid_from` and `valid_to` timestamps. No window functions, no Go code — just hash aggregation parallelised across CPU cores (~25 min).
3. *Materialize* (Phase 3): The Parquet files are loaded into an indexed DuckDB `.db` file (130 GB) for point-lookup queries (~5 min).

The SCD2 design exploits the fact that each AT Protocol record has a unique URI with at most one create and one delete event. 

The resulting graph contains $28.9 times 10^6$ users with $1.47 times 10^9$ active follow edges. Approximately 75% of users follow at least one other user; the average follows per active user is ~68. The full ingestion specification is in @apx-topology.

=== Graph Sampling

The complete 29-million-node follow graph is far too large for agent-based simulation at hundreds of replications. Smaller subgraphs must be sampled while preserving the power-law degree distribution characteristic of social networks @kwak2010twitter.

The sampling strategy uses Forest Fire sampling @leskovec2006sampling, which simulates a spreading process: starting from a random seed node, the sampler "burns" a fraction $p_f$ of the node's outgoing neighbours (forward burning) and $p_b$ of its incoming neighbours (backward burning), recursively visiting the newly discovered nodes. This produces subgraphs that preserve the heavy-tailed degree distribution, community structure, and clustering coefficient of the original network — properties that simpler methods like random node or random edge sampling fail to replicate.

The implementation (`topology/sampling-go/main.go`) loads active follow edges from Parquet as a binary edge list, builds an in-memory CSR adjacency ($1.47 times 10^9$ edges), and runs the Forest Fire algorithm with $p_f = 0.5$, $p_b = 0.2$ to seven target sizes: $10^4$, $5 times 10^4$, $10^5$, $2.5 times 10^5$, $5 times 10^5$, $7.5 times 10^5$, $10^6$ nodes. Two edge sets are output per snapshot: *burned edges* (only those traversed by the fire) and *induced edges* (all edges between visited nodes). The induced subgraph is the topology used for simulation.

Seven datasets are generated, one per target node count: $10^4$, $5 times 10^4$, $10^5$, $2.5 times 10^5$, $5 times 10^5$, $7.5 times 10^5$, and $10^6$ nodes. This gradation enables convergence studies across network sizes, from tractable pilot runs to larger-scale experiments approaching realistic social graph densities. The full ingestion, extraction, and sampling pipeline is detailed in @apx-topology.
