#import "../utils.typ": *

Following the required conventions of Universitat Politècnica de Catalunya @upc-ia-guia, this annex specifies which generative-AI tools have been used and for which purpose.

== Models

The following models have been used at any point during the creation of this work.
- Google Gemini 3.1 Pro @gemini-3-1-pro: via Browser Chatbot and briefly via API.
- Google Gemini 3.5 Flash @gemini-3-5-flash: via Browser Chatbot.
- Google Gemini 3.6 Flash @gemini-3-6-flash: via Browser Chatbot.
- DeepSeek v4 Pro @deepseek-v4: via API with Pi agent harness.
- DeepSeek v4 Flash @deepseek-v4-flash: via API with Pi agent harness.
- MoonshotAI Kimi K3 @kimi-k3: via API with Pi agent harness.

== Tools

The used tools for Generative AI usage are mainly the Google Gemini app @gemini-app, which offers a chatbot interface to talk to the Gemini family models, and Pi @pi-dev, a terminal-based coding agent harness.

Pi wraps an LLM ---in this work the DeepSeek and Kimi models, accessed through their APIs--- and gives it direct access to the working repository: it can read, edit, and run code, and is steered by the author through prompts. It has been the main interface for all the agentic coding work described below, and can be regarded as a methodology in its own right, since it turns the model from a conversational assistant into an agent that operates directly on the codebase.

== Regarding Code

Every model has been used for specific purposes, especially taking into account its coding capabilities and cost. We can classify the models in the following categories.
- Gemini 3.1 Pro, Kimi K3: used for methodological questions and doubts as well as architectural decisions. These models were often used in what programmers call the "rubber duck" @hunt1999pragmatic strategy, which consists in verifying your understanding of a process, piece of code, or concept by talking it out loud. With the more costly AI agents, they can help you catch a blind spot you might have missed.
- DeepSeek v4 Pro: used mostly for sensitive coding tasks and some back and forth on ideas.
- DeepSeek v4 Flash, Gemini 3.6 Flash: small syntax coding questions and structural or small refactors.

Regarding this, and to explain my approach to the code of this thesis, I will make some definitions to classify the behaviour properly.

#def(name: "Programming")[
  Action performed by a programmer. It is characterized by writing code that satisfies certain criteria and executes the expected functionality.
] <def-programming>

#def(name: "Agentic Engineering")[
  Action performed by not necessarily a programmer, nor by someone with deep knowledge of programming. Programs are generated by LLM agents, which follow the instructions of the engineer to the best of their abilities. The engineer should verify the proper functioning of the program by exhaustive testing or by reading the code, according to their abilities.
] <def-agentic-engineering>

#def(name: "Vibe Coding")[
  Characterized by a complete disregard for the code output of the machine, leaving the engineer knowing nothing about the codebase that the AI agents have generated.
] <def-vibe-coding>

The author of this work is ---but not only--- a programmer, and therefore knows how to program, which makes this work fall under the umbrella of the @def-programming. Specifically, the action of "programming", as understood in the definition, has been performed extensively in this work, in everything core to the simulation. That includes:
- `PauSolerValades/des-ctic/bksysim`: the simulation itself, including code and architecture.
- `PauSolerValades/distributions`: the distribution library the simulation fundamentally depends on.
- `PauSolerValades/eazy-args`: the argparsing library.
- `PauSolerValades/ds-bskysim`: all data structures used by the simulation.
- `PauSolerValades/des-ctic/cascade`: the cascade construction code and architecture.
- `PauSolerValades/tabular`: reading and writing tsv.
- `PauSolerValades/des-ctic-progress`: the successive iterations of the simulation that preceded the final `des-ctic` repository.

That does not mean AI has not been used to ask questions, search for bugs or misbehaviours, or do tangential coding work. This work methodology is not an ethics question, but the fundamental conclusion of what a simulation is.

If someone presents code as sensitive as a simulation, where the shape of the problem is deeply unknown and complex, but cannot explain the reasoning of every single line of code written, do not trust the results of that program. The iteration process is needed to understand what works and what does not, and every small decision must have been taken by the human in order to describe the simulation. Everything is critical code by nature, not due to its importance, but to its significance.

Another reason is the current inability of LLMs to take reasonable performance decisions unless constantly nudged into caring about them, especially in a sub-1.0 language like Zig. These two reasons have made the core of this work profoundly non-LLMed, whether that is a good or a bad thing.

Regarding the data analytics repositories the methodology has been closer to an agentic engineer under the @def-agentic-engineering definition, as there was a very substantial quantity of code to write without being very critical in nature.

`PauSolerValades/bsky-data-analysis` contains the analysis of the raw Bluesky firehose used to calibrate the simulation: the exploratory analysis of the event stream, the reconstruction of user sessions together with their duration and inter-session times, the inter-post gaps within a session, the post lifetime, and the structural virality of repost cascades. `PauSolerValades/bskysim-data-analysis` contains the analysis of the simulation *output*: the warmup and stationary-regime experiments, the post-lifetime and distribution fitting over the simulation traces, and the RAM and time-complexity analysis of the final runs.

In both cases the bulk of the scripts ---mostly Python, SQL, and plotting code--- was generated by the LLM through Pi and then supervised and read by the author to verify its functioning. The reason behind that is that all the data analysis has been using pretty standard tools the LLMs excel at doing.

Lastly, I hereby swear that, in any case and under any circumstance, the code in any of the repositories that compose this work is incompatible with the vibe-coding definition @def-vibe-coding. It might be suited to quick prototyping or self-use software, but it is unacceptable, in the author's view, in any kind of professional or academic setting.

== Regarding the Report

The writing of this report has been assisted with AI, especially in the time-consuming processes such as table making or figure composition. Additionally, it has been used to clarify hard-to-understand parts and to review grammar automatically, together with the Pi coding agent.

== Regarding Research

Additionally, LLM models have been used as a quick path to current state-of-the-art ways of performing different tasks not previously performed by the author, and to attempt to validate the proper methodology. It has been quite useful indeed to find relevant papers together with Google Scholar @google-scholar, which now incorporates a natural language search mode.
