// Discarded post-creation distribution analyses. This file is NOT included in the thesis.
// It preserves the alternative approaches explored to characterize the within-session
// inter-post creation gaps, all of which were rejected in favor of empirical (ECDF) sampling:
// truncation simulation, the independence permutation test, and pooled parametric fits.
// Kept in the thesis: Global Creation Distributions, Within-Session Goodness-of-fit and
// the Per-Pair Posts per Session and Within ECDFs (see src/annex/postcreation.typ).
#import "../utils.typ": *

== Truncation Simulation
<apx-interpost-truncated>

Within-session gaps are only observable when the session is long enough to contain both posts: the observation process is $x | x < T$ with $T$ the session length (median $110$ s, p99 $1710$ s; see @tbl-cal-session-stats). To quantify what this does to family identification, `validate_truncated.R` simulates each candidate family, keeps the draws below a session-like ceiling $T$, and refits the survivors with the same untruncated candidates and AIC as the production pipeline (30 replicates per family, ceiling and sample size).

@tbl-apx-interpost-confusion shows the resulting confusion matrix at $n = 100$ (pooled over all ceilings): every light-tailed family is systematically classified as power-law in roughly a third to two thirds of replicates ---truncation manufactures power-law wins. The recovery table (@tbl-apx-interpost-acc) shows the ceiling dependence at both sample sizes: at $T <= 300$ s the light families sit at or below chance level, and even $n = 100$ observations do not help; they only separate at $T >= 900$ s. Since within gaps have p90 = 281 s, the whole within-session quantity lives in the unidentifiable regime and no within family composition is reportable (see @sec-cal-interpost).

#figure(
  table(
    columns: 7,
    align: (left, center, center, center, center, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [], table.vline(stroke: 0.5pt), [*Exp*], [*Gamma*], [*Lognorm*], [*Weibull*], [*Fisk*], [*Power-law*],
    table.hline(stroke: 0.5pt),
    [*Expon*], [30.7], [2.7], [0.0], [5.3], [0.0], [61.3],
    [*Gamma*], [0.0], [30.0], [4.0], [31.3], [0.0], [34.7],
    [*Lognorm*], [0.7], [15.3], [31.3], [19.3], [6.0], [27.3],
    [*Weibull*], [2.0], [45.3], [0.0], [22.0], [0.0], [30.7],
    [*Fisk*], [0.0], [12.7], [17.3], [14.0], [20.0], [36.0],
    [*Power-law*], [14.7], [2.7], [3.3], [9.3], [2.7], [67.3],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Truncation-simulation confusion matrix ($n = 100$).],
    [Share of replicates (%) where AIC picks each family (columns), pooled over ceilings $T in {60, 120, 300, 900, 3600}$ s and 30 reps per family; rows are the true families. Light-tailed data is systematically classified as power-law.],
  )
) <tbl-apx-interpost-confusion>

#figure(
  table(
    columns: 7,
    align: (left, center, center, center, center, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Family*], [*n*], [*60 s*], [*120 s*], [*300 s*], [*900 s*], [*3600 s*],
    table.hline(stroke: 0.5pt),
    [Expon], [30], [0.0], [0.0], [60.0], [66.7], [63.3],
    [Expon], [100], [0.0], [0.0], [6.7], [73.3], [73.3],
    [Fisk], [30], [0.0], [0.0], [0.0], [10.0], [16.7],
    [Fisk], [100], [0.0], [0.0], [0.0], [33.3], [66.7],
    [Gamma], [30], [0.0], [3.3], [30.0], [30.0], [36.7],
    [Gamma], [100], [0.0], [0.0], [36.7], [56.7], [56.7],
    [Lognorm], [30], [0.0], [6.7], [26.7], [66.7], [53.3],
    [Lognorm], [100], [0.0], [0.0], [6.7], [76.7], [73.3],
    [Power-law], [30], [86.7], [80.0], [56.7], [3.3], [16.7],
    [Power-law], [100], [93.3], [96.7], [63.3], [23.3], [60.0],
    [Weibull], [30], [0.0], [0.0], [6.7], [20.0], [30.0],
    [Weibull], [100], [0.0], [0.0], [0.0], [53.3], [56.7],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Truncation-simulation family recovery by ceiling.],
    [Share of replicates (%) where AIC recovers the true family, by ceiling $T$ and sample size $n$ (30 reps per cell; chance level is 16.7%). Light families separate only at $T >= 900$ s; power-law's early high recovery is the manufactured-wins flip side ---at low ceilings the classifier defaults to power-law for every family.],
  )
) <tbl-apx-interpost-acc>

== Independence Permutation Test
<apx-interpost-independence>

The temptation the ECDF decision had to resist: the global quantity is easy to model and the within one is not, so derive the within from the global. If posts were generated by a single session-blind process, within gaps would be the global gaps that happen to fall inside session windows, and the simulator would only need the global model plus the session gate it already has (the staleness rule drops creates that land past session end). One distribution instead of five, zero new code. This appendix shows the derivation fails ---with an exact permutation test and two descriptive replays--- and that the failure is informative: it rules out not just the naive gate but also the natural parametric repair, leaving the ECDF of @sec-cal-interpost-ecdf as the justified rather than merely convenient choice.

=== Hypotheses and Test Statistic

Let ${T_i}$ be a user's post times and ${[S_j, E_j]}$ their session windows. H0 (independence): the post process is independent of the window process ---given the gap sequence, the alignment between posts and windows is uniform; windows observe the stream, they do not modulate it. H1: posting is coupled to session state (rate modulation). The test statistic is the number of within-session pairs, $N = sum_i bb(1)[exists j: S_j <= T_i < T_(i+1) <= E_j]$, one-sided (H1 predicts $N_"obs" > N_"null"$).

A parametric test was deliberately avoided: any likelihood-based test needs a model of the post process under H0, which is heavy-tailed, user-specific and serially correlated (burstiness). A wrong null model would confound "the model is wrong" with "the coupling exists". A permutation test needs no model of the gaps at all: it conditions on the user's _observed_ gap sequence and randomizes only the quantity H0 says is irrelevant ---the alignment.

=== The Null Ensemble and the Result

Under H0, given the ordered gap sequence and the window layout, the time origin of the stream relative to the windows is uniform. The exact randomization is therefore a circular time-shift: wrap the real span into a circle and rotate by $U tilde "Uniform"(0, t_n - t_0)$. This preserves _everything_ about the user's behavior ---every gap value, their order, all autocorrelation and burst structure, the window layout--- and destroys only the post↔window alignment. It is the maximal preserving randomization: any residual difference must be attributed to the alignment itself. (An iid bootstrap of the gaps would also destroy serial structure, leaving the test open to the objection that burstiness, not alignment, drove the rejection; it is retained below only as a probe.)

Result (1,000 users sampled from the global $n_"obs" >= 30$ pool; 920 with at least 5 real within pairs enter the test; $R = 999$ shifts each):

#figure(
  table(
    columns: 2,
    align: (left, right),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Quantity*], [*Value*],
    table.hline(stroke: 0.5pt),
    [Users rejecting H0 at $alpha = 0.05$], [920 / 920 (100%)],
    [Median per-user p], [0.001 (resolution floor)],
    [Fisher combined], [$chi^2 = 12,679$ on 1,840 df],
    [Observed / median-null pair count (per-user median)], [21 times],
    [Null produces < half the observed pairs], [100% of users],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Permutation test result: H0 (session-independent posting) is rejected for every testable user.],
) <tbl-apx-interpost-perm>

The rejection is not marginal: for essentially every user, _no_ random alignment of their own posting rhythm comes anywhere near the observed within-session density. Posting is coupled to session state.

=== Decomposition Probes

The test establishes _that_ the alignment matters; two descriptive replays establish _how_. They are not part of the test and carry no p-values; they guide the modeling decision (@fig-cal-interpost-independence).

- *iid replay --- rate, not shape.* Bootstrap the user's own empirical global gaps into a fresh stream (same span, t0 = first real post) and replay against the real windows. Count: median real/synth ratio 19 times, and synthetic reaches at least 5 within pairs for only 9--11% of users. Shape: among gate-surviving pairs, per-user median(real)/median(synth) = 1.02, p75 identical. Within gaps are not specially _short_; they simply occur far more often while inside a session. Modulation is in rate, not shape.
- *conditional-truncation replay --- the smart repair, rejected.* Keep the global model but inside each session sample gaps conditioned on fitting the remaining session time, walking the session from its start. The repair overshoots: median real/cond ratio 0.3 times (~3 times too many within pairs), and the synthetic gaps are too short (pooled medians 49 s vs 95 s; per-user ratio 2.03). Conditioning a heavy-tailed law on $x <=$ (small remaining time) concentrates mass on tiny gaps, and re-conditioning on the _shrinking_ remaining time drifts successive draws shorter still ---systematically shorter than anything real in-session behavior produces.

The verdict (count and shape relative to the real within distribution):

#figure(
  table(
    columns: 3,
    align: (left, center, center),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Model for within*], [*Count*], [*Shape*],
    table.hline(stroke: 0.5pt),
    [Global, session-gated (H0)], [19 times too few], [Right],
    [Global, truncated (repair)], [3 times too many], [2 times too short],
    [Own law (ECDF)], [---], [---],
    table.hline(stroke: 0.8pt),
  ),
  caption: [Verdict of the two replays: no deformation of the global distribution reproduces the within distribution.],
) <tbl-apx-interpost-verdict>

The truth lies strictly _between_ the two parametric reductions: within gaps are shorter than global gaps (something changes when online) but longer than truncated-global gaps (it is not rejection sampling from the global law). The within cadence is its own law.

#figure(
  image("../../images/calibration/interpost_independence_ecdf.png", width: 100%),
  caption: flex-caption(
    [Real vs. replayed within-session gaps.],
    [ECDFs of real within-session gaps and of the two replays: an iid bootstrap of the user's own global gaps, and a conditional-truncation walk of the session. The shapes coincide; the counts do not.],
  )
) <fig-cal-interpost-independence>

=== The Closed Routes

All three cheap routes are now closed:

1. *Session-independent posts* (sample global, let the gate produce within) ---disproved by the permutation test above.
2. *Conditional-truncation sampling* from the global fits ---disproved by the second probe.
3. *Truncated-likelihood parametric fits* of the within quantity (e.g. fitdistrplus + truncdist) ---statistically valid in principle, but the truncation point varies per pair (remaining session time, not a fixed bound), demanding a custom likelihood, and estimates remain high-variance in the regime of @apx-interpost-truncated (ceiling on the bulk; light families separable only at $T >= 900$ s while within p90 = 281 s). Out of scope.

Hence the ECDF sampling of @sec-cal-interpost-ecdf, chosen by elimination rather than by convenience.

=== Ontology Note

Neither test nor probes privilege the global quantity as the "natural" process. Users can only post while online, so the generative decomposition runs the other way: global gaps are a two-component mixture ---within-session gaps and cross-session spans (session remainder + offline wait + next-session offset)--- and the dominant lognormal global fits are single families stretched over that mixture, compressions rather than behavioral laws. The simulator reflects the correct direction: sessions and within cadence are the two generative components, and the global distribution survives only as a user-level heterogeneity label selecting which per-family ECDF to load. The global counterfactual was nevertheless indispensable: only by rejecting the session-blind model can the two-component design be justified over the cheaper one-component one.

=== Threats to Validity

- *Window--post circularity.* Sessions are built from all events _including_ posts, so windows and post times are coupled by construction. Likes dominate events ~5:1 over posts, so windows are mostly like-defined; the shift null preserves windows, gaps and order, so the rejection isolates the alignment, not window formation.
- *Resolution floor.* With $R = 999$ the smallest reportable p is 0.001; the true per-user p-values are likely far smaller (the median null count is 21 times below observed).
- *User pool.* The test conditions on >= 30 global gaps and >= 5 within pairs ---active users. This is the population that matters for the simulator's posting dynamics; casual users contribute few posts either way.
- *Span wrap.* The circular shift treats the observed span as a torus; for users whose span is dominated by one long gap, a shift can concentrate posts artificially. This affects the null, is shared across users, and would have to systematically deplete within pairs 21-fold to explain the result ---implausible, and the iid probe (no wrap) shows the same deficit.

== Pooled Parametric Fits
<apx-interpost-pooledfit>

Per-user fits are unidentifiable (Finding 1, @apx-interpost-truncated) and the permutation test closed the derivation routes (@apx-interpost-independence); the chosen route is ECDF sampling. One question remains open: can _one_ distribution with _one_ parameter set describe the within-session gaps of a whole user group? Two groupings were tried (`pooled_fit.py`, same 8-candidate MLE battery and closed-form KS/CvM/AD as @apx-method-gof-dist, scipy instead of fitdistrplus): everyone pooled (1M uniform subsample of all 11.1M within gaps) and per (duration $times$ gap) pair ---users grouped by their settled parametric type pair, within gaps pooled per pair (250k gaps each).

=== Everyone Pooled

@tbl-apx-interpost-pooled shows the result on the full pool. The AIC winner is gamma ---a light tail--- and the heavy-tail look of the pooled histogram is a mixture artifact: pooling heterogeneous users manufactures an apparent heavy tail that no single heavy-tailed family fits (lognorm and fisk lose by more than $150,000$ AIC; pareto degenerates).

#figure(
  table(
    columns: 7,
    align: (left, center, center, center, center, center, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Family*], [*k*], [$Delta "AIC"$], [*KS*], [*CvM*], [*AD*], [*Parameters*],
    table.hline(stroke: 0.5pt),
    [Gamma], [2], [0], [0.0351], [216.19], [2,082], [shape 0.845, scale 151.1],
    [Weibull], [2], [1,310], [0.0390], [293.20], [2,674], [0.902, 121.6],
    [Exp], [2], [4,008], [0.0626], [501.07], [384,841], [scale 126.7],
    [Lomax], [2], [7,285], [0.0516], [308.93], [4,094], [11.19, 1298],
    [Generalized Pareto], [2], [7,285], [0.0516], [308.93], [4,094], [0.089, 116.0],
    [Fisk], [2], [167,728], [0.0722], [1,387.84], [15,063], [1.268, 74.95],
    [Lognorm], [2], [203,187], [0.0993], [3,690.51], [23,583], [$sigma$ 1.448, scale 63.6],
    [Pareto], [2], [1,472,452], [0.3419], [41,017.27], [573,517], [degenerate (shape 0.24, scale $->$ min)],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Pooled 8-family fits of the within gaps (1M gaps).],
    [MLE fits of all within-session gaps pooled over all users, ranked by AIC. The gamma winner is a light tail: the heavy-tailed look is a mixture artifact. AD rejects every family catastrophically (best 2,082 vs critical $approx 2.5$): the real ECDF has a burst floor at 1--10 s and a sharp kink at the session ceiling that no 2-parameter family reproduces (@fig-apx-interpost-pooled-ecdf).],
  )
) <tbl-apx-interpost-pooled>

#figure(
  image("../../images/annex/interpost_pairs/pooled_fit_ecdf.png", width: 100%),
  caption: flex-caption(
    [Pooled within-gap ECDF vs top fitted CDFs.],
    [ECDF of the pooled within-session gaps (log-x) against the fitted gamma, Weibull and exponential CDFs. The burst floor and the session-ceiling kink are visible; AD rejects every candidate.],
  )
) <fig-apx-interpost-pooled-ecdf>

=== Per (Duration $times$ Gap) Pair

Restricting to (supposedly) homogeneous users makes the case stronger for a single parametric law. @tbl-apx-interpost-pooledpairs shows the AIC-best and AD-best per pair (the AD of the AIC winner in bold when catastrophic). The fit degenerates worse than pooled:

- *AIC and AD contradict each other in roughly 9 of 16 pairs.* Expon wins AIC in 8 pairs (the bulk is near-exponential), but its AD there is catastrophic (8k--93k, often the worst serious family): it fits the bulk and misses the tail, and AD weights exactly the tail. No winner is criterion-robust.
- *AD rejects everything everywhere.* Best AD across all pairs is $approx 161$ vs critical $approx 2.5$. Restricting to homogeneous users does not fix it: the session-ceiling kink exists inside every pair.
- *Winner identity is unstable across pairs* (gamma, weibull, expon, fisk and lognorm each win somewhere, several near-ties) although the shapes are visually near-identical: family choice is noise, not signal.

#figure(
  table(
    columns: 5,
    align: (left, center, center, center, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*Pair (duration $times$ gap)*], [*AIC-best*], [$Delta "AIC"$ to 2nd], [*AD of AIC-best*], [*AD-best family (AD)*],
    table.hline(stroke: 0.5pt),
    [Exp $times$ Lognorm], [Gamma], [5,745], [224], [Gamma (224)],
    [Exp $times$ Power-law], [Weibull], [640], [277], [Weibull (277)],
    [Exp $times$ Weibull], [Gamma], [4,825], [264], [Gamma (264)],
    [Gamma $times$ Lognorm], [Gamma], [206], [211], [Weibull (161)],
    [Gamma $times$ Power-law], [Weibull], [1,487], [626], [Weibull (626)],
    [Gamma $times$ Weibull], [Weibull], [358], [213], [Weibull (213)],
    [Lognorm $times$ Lognorm], [Exp], [741], [*13,628*], [Weibull (255)],
    [Lognorm $times$ Power-law], [Exp], [2,944], [*93,414*], [Gamma (844)],
    [Lognorm $times$ Weibull], [Exp], [2,305], [*20,143*], [Gamma (210)],
    [Power-law $times$ Lognorm], [Fisk], [2,788], [724], [Gamma (716)],
    [Power-law $times$ Power-law], [Exp], [2,151], [*15,957*], [Gamma (274)],
    [Power-law $times$ Weibull], [Exp], [413], [*22,156*], [Fisk (692)],
    [Weibull $times$ Fisk], [Exp], [1,552], [*13,902*], [Gamma (266)],
    [Weibull $times$ Lognorm], [Lognorm], [747], [819], [Fisk (745)],
    [Weibull $times$ Power-law], [Exp], [980], [*8,677*], [Gamma (344)],
    [Weibull $times$ Weibull], [Exp], [35 (coin-flip vs Lomax)], [*67,685*], [Lomax (599)],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Per-pair pooled fits of the within gaps (250k gaps each).],
    [AIC-best and AD-best family for the within gaps pooled over each (duration, gap) pair. The AD of the AIC winner is bold when catastrophic: AIC and AD contradict each other in most pairs, and no winner is criterion-robust.],
  )
) <tbl-apx-interpost-pooledpairs>

=== Conclusion

The per-pair ECDFs already exist and are exactly the files the simulation loads (`results/within_ecdf__<dur>__<gap>.txt`, see @apx-interpost-pairs). A parametric law per pair is formally rejected everywhere and adds nothing the ECDF does not already encode exactly (burst floor, ceiling kink). The pair split is the finer-grained replacement for the coarser per-global-family ECDFs: the simulation assigns each user their (duration, gap) pair and loads the matching ECDF.

