#import "../utils.typ": *

This section aims to explain the effort taken into easy reproducibility and trace analysis, as well as give an insight of why this software is needed.

First, to give context of the data generated by the simulations, @tbl-pipeline-per-run and @tbl-pipeline-total reports the average lines and size per run, as well as total lines and size for all the runs, in binary and in jsonl.

#figure(
  table(
    columns: 6,
    align: (left, left, right, right, right, right),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*size*], [*type*], [*lines*], [*bin GB*], [*jsonl GB (est)*], [*lines/file avg*],
    table.hline(stroke: 0.5pt),
    table.cell(rowspan: 5, [10K]), [action], [226.0M], [9.04], [29.9], [2.26M],
    [session], [14.4M], [0.58], [1.57], [144K],
    [create], [24.0M], [0.77], [2.17], [240K],
    [propagation], [26.7M], [0.86], [2.44], [267K],
    [swap], [9.37M], [0.15], [0.62], [94K],
    table.cell(rowspan: 5, [50K]), [action], [1.34B], [53.6], [177.3], [13.4M],
    [session], [71.1M], [2.84], [7.76], [711K],
    [create], [125.2M], [4.01], [11.3], [1.25M],
    [propagation], [141.2M], [4.52], [12.9], [1.41M],
    [swap], [46.0M], [0.74], [3.06], [460K],
    table.cell(rowspan: 5, [100K]), [action], [2.78B], [111.1], [367.7], [27.8M],
    [session], [141.8M], [5.67], [15.5], [1.42M],
    [create], [252.7M], [8.09], [22.8], [2.53M],
    [propagation], [286.1M], [9.16], [26.1], [2.86M],
    [swap], [92.1M], [1.47], [6.13], [921K],
    table.cell(rowspan: 5, [500K]), [action], [15.05B], [601.9], [1991], [150.5M],
    [session], [708.4M], [28.3], [77.3], [7.08M],
    [create], [1.30B], [41.5], [116.9], [13.0M],
    [propagation], [1.48B], [47.2], [134.8], [14.8M],
    [swap], [474.9M], [7.60], [31.6], [4.75M],
    table.cell(rowspan: 5, [1M\*]), [action], [24.69B], [987.8], [3268], [271.4M],
    [session], [1.28B], [51.2], [139.8], [14.1M],
    [create], [2.29B], [73.1], [206.2], [25.1M],
    [propagation], [2.58B], [82.6], [235.8], [28.4M],
    [swap], [872.8M], [14.0], [58.1], [9.59M],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Per-run data volume by cohort size and record type.],
    [Average lines and size per run for each record type, and the total across all runs, in binary and estimated jsonl.],
  )
) <tbl-pipeline-per-run>

#figure(
  table(
    columns: 4,
    align: (left, right, right, right),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*size*], [*total lines*], [*bin (GB)*], [*jsonl*],
    table.hline(stroke: 0.5pt),
    [10K], [300.5M], [11.4], [36.7 GB],
    [50K], [1.72B], [65.7], [212.4 GB],
    [100K], [3.55B], [135.5], [438.3 GB],
    [500K], [19.0B], [726.5], [$approx$ 3.6 TB],
    [1M], [31.7B], [1208.7], [$approx$ 5.7 TB],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption(
    [Total data volume per cohort size.],
    [Total lines and size aggregated over all runs of each cohort size, in binary and estimated jsonl.],
  )
) <tbl-pipeline-total>

This put us in perspective of how much raw data must be processed per run, that has to be processed. In order to schedule the processes consistently we have created a pipeline, which processes the traces, creates the cascades files per run `.tsv` (@apx-pipeline-cascades) and with those outputs generate the datasets @apx-pipeline-datasets. This is scheduled using the Zig build system by managing the programs execution as a make file (@apx-pipeline-build) in order to automatically ran them sequentially over the newly generated data. 

== Construct Cascades
<apx-pipeline-cascades>

Construct cascades is the `construct-cascade` Zig project (in `des-ctic/cascade`) that stitches the creation, propagation and repost traces into a single cascade per post.

The program does not read the `action.jsonl` shown in @code-action-sample ---that is the human-readable form of the action trace--- but its binary counterpart (see @sec-design-traces): `{run}-create_trace.bin`, `{run}-propagation_trace.bin` and `{run}-action_trace.bin`. From the action trace it keeps the `repost` decisions (dropping `ignore` and routing `like` to a separate file), and combines them with the creations and propagations into the `cascades.tsv` format shown in @code-cascades-sample.

#code(caption: flex-caption([Sample of the `action.jsonl` trace.], [Sample of the `action.jsonl`. `gen_id` has been omitted for brevity]))[
  ```json
  {"time":41.96,"event_id":41,"user_id":3599,"post_id":708,"parent_id":708,"type":"like"}
  {"time":67.85,"event_id":42,"user_id":2923,"post_id":708,"parent_id":708,"type":"like"}
  {"time":1218.74,"event_id":43,"user_id":6167,"post_id":708,"parent_id":708,"type":"ignore"}
  {"time":1240.10,"event_id":44,"user_id":8059,"post_id":708,"parent_id":708,"type":"repost"}
  {"time":1242.55,"event_id":45,"user_id":6070,"post_id":708,"parent_id":8059,"type":"like"}
  {"time":1243.01,"event_id":46,"user_id":3452,"post_id":708,"parent_id":8059,"type":"ignore"}
  {"time":1245.62,"event_id":47,"user_id":3055,"post_id":708,"parent_id":8059,"type":"like"}
  {"time":1246.89,"event_id":48,"user_id":9598,"post_id":708,"parent_id":8059,"type":"repost"}
  {"time":1248.11,"event_id":49,"user_id":5368,"post_id":708,"parent_id":9598,"type":"like"}
  {"time":1250.03,"event_id":50,"user_id":4771,"post_id":708,"parent_id":9598,"type":"ignore"}
  ```
] <code-action-sample>

#code(caption: flex-caption([Sample of the `cascades.tsv` output.], [Two cascades in the `cascades.tsv` output, for post 708 and 2000. Columns are tab-separated in the file, shown space-aligned here for clarity. `creation` seeds the root, `propagation` marks the post reaching followers, and `repost` records an adoption; `parent_id` links each repost to the user it was seen through (`-1` for the root's own propagation). Events are grouped by type, so all `propagation` rows precede the `repost` rows of a cascade.]))[
  ```tsv
  run_id  post_id  user_id  parent_id  type         time
  0       708      708      708        creation     1
  0       708      708      -1         propagation  2
  0       708      3599     -1         propagation  42.96
  0       708      2923     -1         propagation  68.85
  0       708      3599     708        repost       41.96
  0       708      2923     708        repost       67.85
  0       2000     2000     2000       creation     1
  0       2000     2000     -1         propagation  2
  0       2000     8059     -1         propagation  1241.10
  0       2000     9598     -1         propagation  1247.89
  0       2000     5368     -1         propagation  1249.11
  0       2000     8059     2000       repost       1240.10
  0       2000     9598     8059       repost       1246.89
  0       2000     5368     9598       repost       1248.11
  ```
] <code-cascades-sample>

This project must be as performant as the simulation itself: a fast simulation feeding a slow data-processing pipeline is an equally annoying bottleneck. That is why this project is also written in Zig and uses several properties of the traces, such as being totally ordered, to reduce to just one read per file. Let's discuss the algorithm in depth.

=== Algorithm

The algorithm is split in two clean parts.

*Part 1*: the create, propagation and action traces together carry every event a cascade needs. The first step is to split them into `buckets` to allow for parallelization and to keep the input manageable. Every bucket should hold roughly the same number of posts, so the workload is split equally; each event is assigned to a bucket by hashing its `post_id` and taking the remainder modulo the number of buckets, as shown in @code-cascade-hash.

#code(caption: flex-caption([Bucket assignment by hashing the `post_id`.], [Bucket assignment by hashing the `post_id` with Wyhash and taking the remainder modulo the number of buckets. The `print` already writes the `tsv` line format.]))[
  ```zig
  const hashed_id = std.hash.Wyhash.hash(0, std.mem.asBytes(&pc.post_id));
  const bucket_id = hashed_id % bucket_writers.len;

  try bucket_writers[bucket_id].print(line_fmt, .{ id, pc.post_id, pc.user_id, -1, "propagation", pc.time });
  ```
] <code-cascade-hash>

As can also be seen in the `print` of @code-cascade-hash, the `tsv` output is already written in this first pass.

*Part 2.* Because each bucket has been split by `post_id`, two guarantees hold:

1. The whole cascade of a `post_id` is inside a single bucket.
2. Within each type (`creation`, `propagation`, `repost`) events are time-sorted, since every trace is written in time order.

From each bucket we then have to collect all the events of the same cascade (`run_id`, `post_id`), sort the cascades, and write them to the result file. To collect every cascade at once, the whole bucket is read into memory#footnote[Each bucket holds a small fraction of the total data, so it fits comfortably in memory.], and its lines are parsed into a `HashMap` keyed by a combined key, whose values are an `ArrayList` of events.

The clever part of the algorithm is the same bit-packing idea as in the Ziggurat implementation ---there, a single random word is split into two values (see @sec-method-rng-ziggurat)--- applied in reverse: the `run_id` and `post_id` are packed into a single word, as shown in @code-cascade-key.

#code(caption: flex-caption([Packing the cascade key.], [Packing `run_id` (high 32 bits) and `post_id` (low 32 bits) into a single `u64`, so sorting on the integer orders cascades by the `(run_id, post_id)` tuple.]))[
  ```zig
  const key = (@as(u64, parsed.run_id) << 32) | @as(u64, parsed.post_id);
  ```
] <code-cascade-key>

Once the map is built, the cascades are sorted by key with `std.mem.sort` @zig-std-sort#footnote[Which sorting algorithm `std.mem.sort` uses was not checked; since the data is mostly sorted, a custom merge could certainly save cycles there.], and each cascade's events are dumped, in order, into the output `cascades.tsv`. Likes are routed to a separate `cascades_likes.tsv` in the same pass.

=== Improvements

- Parallelization: especially noticeable in the 1M runs --- every bucket can be sorted and written independently.
- Parquet implementation: writing a TSV in step 1 and re-parsing it in step 2 is wasteful and slow; the same improvement the whole simulation could use.
- Sorting: knowing the data is mostly sorted within each type, there must be a faster way to merge them that does not require a full sort.

== Dataset Creation
<apx-pipeline-datasets>

Once the dataset `cascade.tsv` is created, we can now generate the analyzable `.parquet` datasets. There are 9 distinct datasets:

+ *Run metrics* (`run_metrics.parquet`) --- one row per run, with the global counters used to validate the simulation against its internal `SimMetrics`.
+ *Users* (`users.parquet`) --- one row per user and run, aggregating their sessions and actions.
+ *Sessions* (`sessions.parquet`) --- one row per session, with its timestamps, duration and per-session action counts.
+ *Post metrics* (`post_metrics.parquet`) --- one row per post, with its engagement counts and conversion rate.
+ *Raw post lifetime* (`raw_post_lifetime.parquet`) --- one row per repost, with propagation timing and inter-repost gaps; this feeds the next dataset.
+ *Post lifetime* (`post_lifetime.parquet`) --- one row per post, aggregating the raw dataset into $T_50$, $T_95$, $T_99$ and time-to-peak.
+ *Cascades* (`cascades.parquet`) --- one row per cascade, with tree metrics (depth, size, out-degree, structural virality).
+ *Broadcast groups* (`broadcast_groups.parquet`) --- one row per parent in a cascade, measuring how fast its audience picks up the content.
+ *Root-to-leaf paths* (`root_to_leaf.parquet`) --- one row per root-to-leaf chain, measuring end-to-end traversal.

Despite generating so many datasets, the both the Methodology and Results section (@sec-method and @sec-results respectively) do not report so many results. This is due to the necessary scope reduction the work suffered, as datasets (4), (5), (6), (8) and (9) are unused and not compared to the real data.

=== Dataset Descriptions

The features of each dataset are described below. Composite primary keys are marked with (pk).

==== Run Metrics

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`total_posts_created`], [posts created in the run],
    [`total_reposts`], [reposts in the run],
    [`total_likes`], [likes in the run],
    [`total_ignores`], [ignores in the run],
    [`total_interactions`], [reposts + likes + ignores],
    [`conversion_rate`], [(reposts + likes) / interactions],
    [`total_sessions`], [sessions started in the run],
    [`total_boredom_ends`], [sessions ended with an empty backlog],
    [`total_max_duration_ends`], [sessions ended with backlog $> 0$],
    [`total_swaps`], [timeline refreshes],
    [`duration`], [simulation duration],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Run metrics dataset features.], [Features of the `run_metrics.parquet` dataset, one row per run.]),
) <tbl-pipeline-run-metrics>

==== Users

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`user_id`], [user identifier (pk)],
    [`num_sessions`], [sessions by this user],
    [`total_reposts`], [reposts across all sessions],
    [`total_likes`], [likes across all sessions],
    [`total_actions`], [likes + reposts + ignores across all sessions],
    [`total_posts_created`], [posts created by this user],
    [`total_swaps`], [timeline refreshes],
    [`avg_session_length`], [mean session duration],
    [`total_online_time`], [sum of all session durations],
    [`boredom_ended_sessions`], [sessions ended with an empty backlog],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Users dataset features.], [Features of the `users.parquet` dataset, one row per user and run.]),
) <tbl-pipeline-users>

==== Sessions

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`user_id`], [user identifier (pk)],
    [`session_num`], [session index per user within a run (pk)],
    [`start_time`], [session start timestamp],
    [`end_time`], [session end timestamp],
    [`duration`], [end_time $-$ start_time],
    [`ended_by_boredom`], [true if the session ended with an empty backlog],
    [`total_actions`], [likes + reposts + ignores during the session],
    [`total_likes`], [likes during the session],
    [`total_reposts`], [reposts during the session],
    [`total_ignores`], [ignores during the session],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Sessions dataset features.], [Features of the `sessions.parquet` dataset, one row per session.]),
) <tbl-pipeline-sessions>

==== Post Metrics

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`post_id`], [post identifier (pk)],
    [`author_id`], [user who created the post],
    [`total_reposts`], [reposts of this post],
    [`total_likes`], [likes of this post],
    [`total_ignores`], [ignores of this post],
    [`conversion_rate`], [(reposts + likes) / (reposts + likes + ignores)],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Post metrics dataset features.], [Features of the `post_metrics.parquet` dataset, one row per post.]),
) <tbl-pipeline-post-metrics>

==== Raw Post Lifetime

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`post_id`], [post identifier (pk)],
    [`author_id`], [user who created the post],
    [`creation_time`], [post creation timestamp],
    [`reposter_id`], [user who reposted],
    [`parent_id`], [user the repost was seen through (pk)],
    [`propagated_time`], [when the post reached the reposter's timeline],
    [`repost_time`], [when the repost was performed],
    [`sitting_in_timeline`], [repost_time $-$ propagated_time],
    [`global_gap`], [time since the previous repost of the post; NULL for the first],
    [`topology_gap`], [time since the previous repost from the same parent; NULL for the first per parent],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Raw post lifetime dataset features.], [Features of the `raw_post_lifetime.parquet` dataset, one row per repost.]),
) <tbl-pipeline-raw-post-lifetime>

==== Post Lifetime

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`post_id`], [post identifier (pk)],
    [`author_id`], [user who created the post],
    [`creation_time`], [post creation timestamp],
    [`last_repost`], [timestamp of the last repost],
    [`total_reposts`], [total number of reposts],
    [$T_50$], [time from creation to 50% of reposts],
    [$T_95$], [time from creation to 95% of reposts],
    [$T_99$], [time from creation to 99% of reposts],
    [`time_to_peak`], [time from creation to the densest repost bin],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Post lifetime dataset features.], [Features of the `post_lifetime.parquet` dataset, one row per post.]),
) <tbl-pipeline-post-lifetime>

==== Cascades

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`post_id`], [post identifier (pk)],
    [`author_id`], [user who created the post],
    [`creation_time`], [post creation timestamp],
    [`cascade_depth`], [maximum depth from the root],
    [`cascade_size`], [total nodes, root included],
    [`max_out_degree`], [maximum children of any node],
    [`structural_virality`], [Wiener-index structural virality],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Cascades dataset features.], [Features of the `cascades.parquet` dataset, one row per cascade.]),
) <tbl-pipeline-cascades>

==== Broadcast Groups

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`post_id`], [post identifier, i.e. the cascade (pk)],
    [`parent_id`], [parent user within the cascade (pk)],
    [`broadcast_size`], [number of children],
    [`mean_gap`], [mean topology gap between consecutive children],
    [`median_gap`], [median topology gap],
    [`gap_trend`], [slope of the gaps; positive = decaying audience],
    [`first_child_time`], [repost time of the first child],
    [`last_child_time`], [repost time of the last child],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Broadcast groups dataset features.], [Features of the `broadcast_groups.parquet` dataset, one row per broadcast group.]),
) <tbl-pipeline-broadcast-groups>

==== Root-to-Leaf Paths

#figure(
  table(
    columns: 2,
    align: (left, left),
    stroke: none,
    table.hline(stroke: 0.8pt),
    [*feature*], [*description*],
    table.hline(stroke: 0.5pt),
    [`run_id`], [run identifier (pk)],
    [`post_id`], [post identifier (pk)],
    [`leaf_user_id`], [user at the end of the path],
    [`path_depth`], [number of hops from root to leaf],
    [`path_total_time`], [time from root to leaf],
    [`traversal_speed`], [path_total_time / path_depth],
    [`gap_trend`], [slope of the inter-hop gaps; positive = deceleration],
    table.hline(stroke: 0.8pt),
  ),
  caption: flex-caption([Root-to-leaf paths dataset features.], [Features of the `root_to_leaf.parquet` dataset, one row per path.]),
) <tbl-pipeline-root-to-leaf>

== Creation

The creation of the dataset receives all data as an input: the four `.parquet`/`bin` traces, the cascades of reposts and likes, and the topology the simulation ran over. From there, the Go program does either of two things:
- for the six DuckDB datasets --- *run metrics*, *users*, *sessions*, *post metrics*, *raw post lifetime* and *post lifetime* --- it calls a preexisting `sql` script that generates the parquet;
- for the three cascade datasets --- *cascades*, *broadcast groups* and *root-to-leaf paths* --- it executes Go code to compute the structural virality and the subcascade metrics. 

Every code is relatively straightforward to look and check, and there are no architectural decisions other than using a CSR (see @apx-impl-csr) to represent the graph again, but this time in Go instead of Zig.

== Orchestration
<apx-pipeline-build>

With all pieces described, we have the following situation if we want to have usable datasets from the simulation:
- Make a run of the simulation, which will have $n$ iterations in $w$ workers, making every worker run a batch of $approx n/w$ iterations, as well as specifying the configuration and the topology as input.
- With the simulation traces as input, specifying the output directory --- and maybe changing the location or number of the buckets, although that is not very common.
- Lastly, provide all the outputs of both `bskysim` and `construct-cascade` to the dataset creation, together with the output directory, in order to obtain the results.

Additionally, all projects must be compiled for the target architecture in `ReleaseFast` mode (and its Go equivalent). As the reader can see, it is very time consuming to write all of this for a single run. This is what justifies the creation of a pipeline, or an orchestrator. Before attempting to write it in Python, despair became apparent, and I turned to the last amazing Zig feature this work will showcase: the build system.

The Zig Build System @zig-build-system is a program of the Zig standard library that allows building a Zig program in Zig. The closest well-known program that implements the same functionality is `make`, which compiles and manages C builds. The strong point of the Zig build system is that, being written in Zig itself, there is no need to learn another language in order to make use of it.

In all Zig projects used by this work, the build system has already been used. For example, to add all the dependencies in the simulation ---the `distribution`, `args` and `data-structures`, `set`--- as well as the `jemalloc` `c_allocator` was specified in the root `build.zig` file.
  
As it is not the objective of this section to explain how it was implemented nor how the Zig Build System works#footnote[An accessible introduction to its basics is available at @zig-build-system], we will describe what has been implemented.

First, all the arguments to all the programs can now be provided with a single JSON file, shown in @code-pipeline-config. The JSON must contain the `simulation`, `cascade` and `dataset` keys, each of which can be `null` to skip that stage.

#code(caption: flex-caption([Example pipeline configuration.], [Example pipeline configuration for a 10K run: `simulation` writes the traces, `cascade` builds the cascade TSVs from them, and `dataset` generates every dataset from both. A `null` section skips that stage; all paths are relative to the repository root.]))[
  ```json
  {
    "simulation": {
      "workers": 8,
      "runs": 100,
      "output_dir": "steps/traces/10K_run",
      "data_file": "data/monotonic/10K_monotonic.bin",
      "config_file": "job_config/prod.json"
    },
    "cascade": {
      "buckets": null,
      "bucket_file": null,
      "output_file": "steps/cascades/10K_run.tsv",
      "traces_dir": "steps/traces/10K_run"
    },
    "dataset": {
      "output_dir": "steps/datasets/10K_run",
      "cascades_ssv": "steps/cascades/10K_run.tsv",
      "likes_ssv": "steps/cascades/10K_run_likes.tsv",
      "traces_dir": "steps/traces/10K_run",
      "dataset": "all"
    }
  }
  ```
] <code-pipeline-config>

All the paths are relative to the root of the repository, where `build.zig` lives, so relative-path problems do not exist. This file must be provided with the option `-Dconfig="path/to/conf.json"`; otherwise the system will not build.

To make it more versatile, several subsets of the pipeline can be run independently:
- `zig build all`: runs the pipeline back-to-back.
- `zig build sim`: runs just the simulation.
- `zig build cascades`: runs the cascades.
- `zig build datasets`: runs the datasets.
- `zig build pipeline`: runs cascades and then datasets.

So if a process gets interrupted midway, we can pick it up with the build system directly.

Lastly, the Build System controls whether the code it calls needs compilation. If the project being called is another Zig project, the integration is tighter, but if it is not, the compilation is performed with a subprocess invocation, as shown in @code-build-compilation.

#code(caption: flex-caption([Compilation control in `build.zig`.], [How `build.zig` controls compilation: the Zig dependencies are declared as artifacts and compiled natively, while the Go binary is built through a `go build` subprocess.]))[
  ```zig
  const sim_exe = b.dependency(
    "bskysim",
    .{ .optimize = .ReleaseFast }
  ).artifact("bskysim");
  b.installArtifact(sim_exe);
  // cascades here, same procedure. skipped for brevity

  // The go binary must be compiled manually
  const go_build = b.addSystemCommand(
    &.{ "go", "build", "-o", "../bin/dataset-creation", "." }
  );
  go_build.setCwd(.{ .cwd_relative = "dataset" });
  b.getInstallStep().dependOn(&go_build.step);
  ```
] <code-build-compilation>
 
This allows us to control and reduce input errors when running the whole simulation, at the same time that being a pleasure to use; especially if one has had the opportunity to atempt a complex coordination stuff with make.
