"""
Generated by Gemini 3.1 Pro based on the following article: https://www.techscience.com/cmc/v73n3/49041/pdf
"""

import os
import random
import json
import argparse


def generate_social_simulator_data(num_nodes=1000, m_edges=3, cc_prob=0.8):
    # --- 1. USERS (Homogeneous Policy) ---
    # Every user shares the exact same policy and action probabilities
    users_data = []
    for i in range(num_nodes):
        users_data.append(
            {
                "id": i,
                "actions": ["ignore", "like", "repost"],
                "policy": [0.5, 0.3, 0.2],
                "max_posts": None,
            }
        )

    # --- 2. FOLLOWERS (Plain Python Graph Generator) ---
    n0 = max(10, m_edges)
    adj = {i: [] for i in range(num_nodes)}

    for i in range(n0):
        left = (i - 1) % n0
        right = (i + 1) % n0
        adj[i].extend([left, right])

    followers_data = []
    for new_node in range(n0, num_nodes):
        targets = set()

        while len(targets) < m_edges:
            start_node = random.randint(0, new_node - 1)
            if not adj[start_node]:
                continue

            neighbor = random.choice(adj[start_node])

            # Clustering Control: 1-step or 2-step walk
            if random.random() < cc_prob:
                target = neighbor
            else:
                target = random.choice(adj[neighbor]) if adj[neighbor] else neighbor

            if target != new_node and target not in targets:
                targets.add(target)

        for t in targets:
            followers_data.append({"follower_id": new_node, "followed_id": t})
            adj[new_node].append(t)
            adj[t].append(new_node)

    # --- 5. EXPORT TO JSON ---
    master_json = {"users": users_data, "followers": followers_data}

    return master_json


if __name__ == "__main__":
    os.makedirs("data", exist_ok=True)

    parser = argparse.ArgumentParser(
        prog="generate_data",
        description="Generates a network topology for a social network",
        epilog="Text at the bottom of help",
    )

    parser.add_argument(
        "num_nodes",
        type=int,
        nargs="?",
        default=100,
        help="Number of nodes in the network",
    )
    parser.add_argument(
        "m_edges", type=int, nargs="?", default=3, help="Number of edges per new node"
    )
    parser.add_argument(
        "cc_prob",
        type=float,
        nargs="?",
        default=0.6,
        help="Clustering control probability",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output file path (default: auto-generated from params)",
    )

    args = parser.parse_args()

    print(
        f"Generating topology with {args.num_nodes} nodes (m_edges={args.m_edges}, cc_prob={args.cc_prob})"
    )

    # Generate the data (keeping m_edges constant gives a true scaling test)
    simulator_dataset = generate_social_simulator_data(
        num_nodes=args.num_nodes, m_edges=args.m_edges, cc_prob=args.cc_prob
    )

    filename = (
        args.output
        or f"data/sn_topo_{args.num_nodes}_{args.m_edges}_{args.cc_prob}.json"
    )

    with open(filename, "w") as f:
        json.dump(simulator_dataset, f)
