#import "@preview/typslides:1.3.3": *

#import "@preview/cetz:0.5.2"
// ==========================================
// GLOBAL CONFIGURATION
// ==========================================
#show: typslides.with(
  ratio: "16-9",
  theme: "bluey",
  font: "New Computer Modern",
  font-size: 18pt,
  link-style: "color",
  show-progress: true,
)

#show heading: set text(font: "New Computer Modern", fill: rgb("#111111"))

// Image base path helper
#let img(path, width: auto) = {
  image("images/" + path, width: width)
}

// Simple grid column helper
#let col2(a, b) = grid(columns: 2, gutter: 2.5em, a, b)
#let col3(a, b, c) = grid(columns: 3, a, b, c)
#let col4(a, b, c, d) = grid(columns: 4, a, b, c, d)


// ==========================================
// PART 1: THE VISION & THE BOTTLENECK
// ==========================================

// --- TITLE SLIDE ---
#blank-slide[
  #v(4%)
  #set align(center)
  #text(size: 1.3em, weight: "bold", fill: rgb("#1a1a1a"))[
    A Continuous-Time Independent Cascade Model \ on Bluesky using Discrete-Event Simulation
  ]
  #v(0.6em)
  #text(size: 1.0em, style: "italic", fill: rgb("#4a4a4a"))[
    Master Thesis — MSc Statistics and Operations Research
  ]
  #v(1em)
  #text(size: 1.0em, weight: "medium")[Pau Soler Valadés]

  #text(size: 0.85em, style: "italic", fill: rgb("#333333"))[
    Supervised by Jana Lasser#super[2], Esteve Codina#super[1], and Pau Fontseca#super[1]
  ]
  #v(0.8em)
  #text(size: 0.75em, fill: rgb("#4a4a4a"))[
    #super[1] Universitat Politècnica de Catalunya #h(1em) #super[2] University of Graz
  ]
  #v(1.2em)
  #text(size: 0.75em, style: "italic", fill: rgb("#666666"))[
    July 23rd of 2026 #sym.dash Facultat de Matemàtiques i Estadística 
  ]
]

// --- SLIDE: The Vision ---
#slide(title: "Context")[
  #set align(center)
  #text(size: 1.1em)[*Objective*: Study Information Diffusion on a Microblogging Social Media.]

  #set align(left)
  #v(0.5em)
  
  *Definition*: Information diffusion is the study of how discrete pieces of content (called from now on posts) propagate through a network infrastructure over time.
  
  When posts propagate, they form *cascades*, trees consisting of the users that see and interact with the post. Therefore,

  #v(0.3em)
  #set align(center)
  #text(size: 1.1em)[_Information Diffusion_ is the study of _Cascades_ generated by _Posts propagation_.]

]

#slide(title: "Cascade Showcase")[

  #set align(center)
  #text(size: 1.5em)[_Show video "Broadcast"_]

  #v(1.5em)
  #text(size: 1.5em)[_Show video "Cascade"_]
]

#slide(title: "Motivation")[
  Cascade analysis is *fundamental* to study: post lifetime analysis and virality of a post.

  *Definition* The _lifetime_ of a post is defined as the time between post creation and the last time someone interacts with this post.

  *Definition* _Structural Virality_ is the *mean distance between any two nodes in a single cascade* 

  $ nu(T) = frac(1, n(n-1)) sum_(i=1)^n sum_(j=1)^n d_(i j) $

  where $T$ is a cascade (a tree) and $d_(i j)$ is the shortest-path distance between nodes $i$ and $j$.
]

#slide(title: "Motivation")[
 
  Those two metrics allow us to detect "rellevant" post:
  - A post with a high lifetime is contagious: an idea that never dies and keeps propagating timewise.
  - A viral post is not just the one that lots of people see ($|T|$ high) but how they connect: it must not be _shallow_ nor _narrow_ but deep and wide *at the same time*



  
  #v(1.0em)
  Being able to both undersand and simulate this can play a big role on society rellevant problems such as 
  + *Echo chambers detection.*
  + *Flagging of misinformation spreaders.*
  + *Understand virality*: what a post says vs who wrote that post. 

]

#slide(title: "This Project")[
  
  Information Diffusion in a Microblogging Social Media site can be characterized by the following by the following three factors:
  - *Platform Affordances:* features of the platform --- feeds, timelines, recommenders. \ _How can a user interact with the content_
  - *User Dynamics:* when users log in --- how long they scroll, how frequently they create.\  _How does the user interact with the platform_ 
  - *User-Content Interaction:* semantic alignment between a post and a user's preferences. \ _Which content does the user interact_

  This project tackles *User-Dynamics* and *Platform Affordances*, specifically excluding _User-Content Interaction_ to mantain a reasonable scope for the project.

  #set align(center)
  #text(size: 1.3em)[*Proposal*: Simulate multiple cascades in real network topology to understand how information diffusion works.]
]

#slide(title: "Parts of the Project")[
  #set text(size: 1.3em) 
  (1) - *Problem Description*: \ What do we want to evaluate and which model do we use
  #v(0.1em)
  (2) - *Model Evaluation*: \ Building a simulation to evaluate the model
  #v(0.1em)
  (3) - *Bluesky Data Analysis*: \ Topology sampling and creation and calibration 
  #v(0.1em)
  (4) - *Simulation Calibration*: \ Which values should the input be
  #v(0.1em) 
  (5) - *Simulation Results*: \ Similarity with real data and results interpretation
  #v(0.1em)
]

#slide(title: "(1) - AT Protocol")[
  Bluesky is a decentralized microblogging platform --- a twitter clone, but built in an open specification, the Authenticated Transfer Protocol, *ATProto*.

  #v(0.7em)
  The ATP decouples data from the application, splitting the view (AppView) from the data --- the *Firehose*.

  #v(0.7em)
  It's easy to listen to all events from the firehose: post creations, reposts, likes, follows, unfollows, blocks...
]


#slide(title: "(1) - Problem Scope")[
  #v(0.2em)
  We model a microblogging social media platform under these simplifying assumptions:

  #v(0.3em)
      - *Just the Following Feed:* reverse-chronological timelines (no recommenders)
      - *Static Users and Followers:* no new users nor follows while the simulation runs.
      - *No Mutes nor Blocks:* following a user means receiving all their posts
      - *No Quotes, no Replies:* only likes and reposts
      - *No User Profiles:* users are limited to their timeline, no browsing other profiles

  #v(0.4em)
  #set align(center)
  #text(size: 1.3em)[A user can only do two things with a post: \ either *like* or *repost*, or just ignore it.]

]

#slide(title: "(1) - Model Intuition")[

  Given a user $u in cal(U)$, it has a timeline $cal(T)_t (u)$ filled with posts $i in cal(I)$. 

  Main idea: user is online, they are *scrolling* through their timelines, and they can interact with a post with a *like* or a *repost*, or just *ignore* it and keep scrolling.

  When $u$ reposts $i$, $i$ *propagates* to the followers of $u$, $cal(N)_"out" (u)$:

  $ "for" v "in" cal(N)_"out" (u): "push"(cal(T)_t (v), i) $

  But $v in cal(N)_"out" (u)$ will not immediately see reposted content $i$ if it has been scrolling for a while, as the user sees _past_ content, so it gets enqueued in $cal(T)_t (v)$.

  When $v$ connects online again and starts scrolling, will eventually see $i$ if the time $v$ has been online is not too long: then $i$ will never have the change to propagate. 

  Also, if a user does not have any new posts to see $cal(T)_t (u) = emptyset$ then will disconnect and connect later.
]

#slide(title: "(1) - Intuition Scene")[
  
  #set align(center)
  #text(size: 1.5em)[_Show video "Queue"_]
]


#slide(title: "(1) - Continuous-Time Independent Cascade")[
  #v(0.3em)
  #text(size: 0.9em, weight: "bold")[*Definition.*] The CTIC model preserves independent transmission across edges but replaces fixed step-based probabilities with a time-dependent transmission likelihood. Each edge has a pairwise transmission rate $alpha_(j,i)$ 
  #v(0.5em)
  #set align(center)
  Once user $u$ propagated a post $i$ at $t_u$ ---assuming $v$ will also propagate it---, follower $v$ will repost $v$ at some latter time $t_v > t_u$ assu
  #v(2em)

 #cetz.canvas({
    import cetz.draw: *
    // Your drawing code goes here
    line((0, 0), (12, 0), stroke: 1pt)
    content((0, -.25), [$t_u$], anchor: "north")
    
    // first tick
    line((0, -0.15), (0, 0.15), stroke: 1pt)
    content((0, .75), [$"prop"(u, i)$], anchor: "south")
    
    // last tick
    line((12, -0.15), (12, 0.15), stroke: 1pt)
    content((12, -.25), [$t_v$], anchor: "north")
    content((12, .75), [$"prop"(v, i)$], anchor: "south")
    
    line((3, -0.15), (3, 0.15), stroke: 1pt)
    content((3, .75), [$i in cal(T)(v)$], anchor: "south")
  
    content((1.5, -.25), [$Delta_p$], anchor: "north")

    content((5, -.25), [$X$], anchor: "north")

    line((7, -0.15), (7, 0.15), stroke: 1pt)
    content((7, .75), [$v$ sees $i$], anchor: "south")

    content((9.5, -.25), [$Delta_a$], anchor: "north")
  })
  
  #text(size: .75em)[Example timeline of the CTIC propagation. The time between $t_u$ and $t_v$ depends on the network, represented by the RV $X$.]
]

#slide(title: "(1) - Activity-Driven & Queue-Based")[

  #v(0.3em)
  *Activity-Driven.* users are not always online interacting. Each user alternates between online sessions and offline periods:

  $ cal(O)(u) = union.big_(k=1)^oo [t_k, t_k + Delta_k) $

  where $Delta_k$ is the session duration.

  #v(0.3em)
  
  *Queue-Based.* Each user's timeline $cal(T)_t(u)$ is a priority queue ordered by arrival time ---the most recently arrived post sits at the top. If the user is online they will be consumed when they go offline.
]

// #slide(title: "(2) - Model Evaluation")[
//   The proposed model is too complex to be analytically evaluated: the use of a simulation is mandatory.
//
//   #v(3em)
//   #set align(center)
//   #text(size: 1.5em)[_Show video "Visualization"_]
//
// ]

// --- SLIDE: ABM vs DES ---
// #slide(title: "Why not Agent-Based Modeling?", back-color: rgb("#fff3e0"))[
//   #col2(
//     [
//       #text(size: 0.9em, weight: "bold")[Agent-Based Modeling]
//       #v(0.2em)
//       - Bottom-up: each user is an autonomous agent with its own perception, state, and decision-making
//       - Even when event-driven, every agent's individual state must still be maintained and evaluated
//       - The agent-centric architecture means effort inherently scales with $N$
//       - High development cost: perception, individual cognition, inter-agent communication
//     ],
//     [
//       #text(size: 0.9em, weight: "bold")[Discrete-Event Simulation]
//       #v(0.2em)
//       - Top-down: entities flow through processes and queues — behavior dictated by system logic, not agent autonomy
//       - Jumps from event to event, bypassing idle intervals entirely
//       - No work for offline users — exploits the *intrinsic sparsity* of human activity
//       - Lean: probability distributions and routing rules, not individual cognition
//     ],
//   )
//
//   #v(0.4em)
//   #text(size: 0.8em)[
//     Both can be event-driven. The difference is philosophical: ABM models *who decides*, DES models *what happens*.
//     When the question is *aggregate diffusion dynamics*, DES routes effort where it matters —
//     the propagation events that actually drive the dynamics — rather than maintaining agent autonomy.
//   ]
// ]



// // --- SLIDE: Simulation Rules ---
// #slide(title: "(2) - Simulation Rules")[
//   #v(0.2em)
//   Let's explicitly state the *rules* that the simulation follows (recap of what seen from now)
//
//   1. A user can just act in three ways over a post: *ignore*, *like* and *repost*.
//   2. A user is either online or offline.
//   3. An offline user cannot do any action.
//   4. A propagation is triggered by a post creation or a repost.
//   5. A propagation by $u$ adds all posts in $cal(N)_"out" (u)$
//   6. Every user has a timeline $cal(T)_t (u)$ which is a reverse-chronological (priority queue, max)
//   7. A user cannot interact with a post that has already interacted.
//   8. If $cal(T)_t (u) = emptyset$, the user goes back offline (boredom).
// ]
//
// --- SLIDE: Input Parameters ---
#slide(title: "(2) - Input Parameters")[
  
  All of this parameters will follow an specified distribution: 
  
  #col2(
    [
      *Global parameters*
      #v(0.15em)
      - Propagation delay $Delta_p$ — time for a post to reach followers
      - Interaction delay — cognitive time before reacting to a post
      - Creation delay — time to compose and publish a post
      - Inter-action time — gap between consecutive timeline checks
      - Policy $pi$: $p_"ignore"$, $p_"like"$, $p_"repost"$
      - Horizon $t_h$ and warm-up $t_w$
      - Offline startup ratio — fraction of users starting offline
    ],
    [
      *User-dependent parameters* (sampled per user)
      #v(0.15em)
      - Session duration $Delta_k$ — how long a user stays online
      - Inter-session gap — offline time between consecutive sessions
      - Inter-post creation — interval between posts authored by the same user
      #v(0.3em)
    ],
  )
]

// --- SLIDE: Event Sources ---
#slide(title: "(2) - Simulation Design")[
  Global queue $Q$ is a min-heap, returns the smallest timestamp event (next event to process)

  A single user can have two sets of events:
  - `session.start`: when is the user going back online.
  - `create`, `action`, `session.end` and `propagate`: Action is to interact with a post, create is to generate a post. If a creation or a repost, a `propagate` event will be triggered in the future and the last is a `session.end`, which turns the user online.

  $Q$ holds *every* events per *every* user. Worse case, 4 events per user, ergo $|Q| approx 4N$.

  Therefore, the *more users* in the simulation, the strained $Q$ will be.

]

// --- SLIDE: Single User Event Timeline ---
// #slide(title: "(2) - Single User Session Timeline")[
//   #v(0.3em)
//   #text(size: 0.85em, weight: "bold")[A single user's session is a chain of events — no propagation, just the user's own activity.]
//
//   #v(2em)
//
//   #cetz.canvas({
//     import cetz.draw: *
//
//     // Main timeline
//     line((0, 0), (18, 0), stroke: 1.4pt)
//
//     // ---- Tick 1: session.start ----
//     line((0, -0.2), (0, 0.2), stroke: 1.2pt)
//     content((0, -.45), [$e_(s)$], anchor: "north")
//     content((0, .85), [*session.start*], anchor: "south")
//     content((0, 1.6), [user goes online], anchor: "south")
//
//     // ---- Tick 2: create ----
//     line((4.5, -0.2), (4.5, 0.2), stroke: 1.2pt)
//     content((4.5, -.45), [$e_c$], anchor: "north")
//     content((4.5, .85), [*create*], anchor: "south")
//     content((4.5, 1.6), [user authors a post], anchor: "south")
//
//     // ---- Tick 3: first action ----
//     line((9.0, -0.2), (9.0, 0.2), stroke: 1.2pt)
//     content((9.0, -.45), [$e_(a_1)$], anchor: "north")
//     content((9.0, .85), [*action*], anchor: "south")
//     content((9.0, 1.6), [like / repost / ignore], anchor: "south")
//
//     // ---- Tick 4: second action ----
//     line((13.5, -0.2), (13.5, 0.2), stroke: 1.2pt)
//     content((13.5, -.45), [$e_(a_2)$], anchor: "north")
//     content((13.5, .85), [*action*], anchor: "south")
//     content((13.5, 1.6), [like / repost / ignore], anchor: "south")
//
//     // ---- Tick 5: session.end ----
//     line((18.0, -0.2), (18.0, 0.2), stroke: 1.2pt)
//     content((18.0, -.45), [$e_(e)$], anchor: "north")
//     content((18.0, .85), [*session.end*], anchor: "south")
//     content((18.0, 1.6), [user goes offline], anchor: "south")
//
//     // ---- Random variable labels below ----
//     content((2.25, -.8), [$Delta_"create"$], anchor: "north")
//     content((6.75, -.8), [$X tilde "Exp"(lambda)$], anchor: "north")
//     content((11.25, -.8), [$Y tilde "Exp"(lambda)$], anchor: "north")
//     content((15.75, -.8), [$Delta_"session"$], anchor: "north")
//
//     // ---- Session span bracket above ----
//     line((0, 1.85), (0, 2.15), stroke: .6pt)
//     line((18.0, 1.85), (18.0, 2.15), stroke: .6pt)
//     line((0, 2.15), (18.0, 2.15), stroke: .6pt)
//     content((9.0, 2.4), [*one session*], anchor: "south")
//   })
//
//   #v(0.8em)
//   #text(size: 0.75em)[
//     Events $e_(s)$, $e_c$, $e_(a_1)$, $e_(a_2)$, and $e_(e)$ form a single user session.
//     Inter-action times $X, Y tilde "Exp"(lambda)$ are i.i.d. between consecutive actions.
//     The session ends at $e_(e)$ — by boredom (empty timeline) or session duration limit.
//   ]
// ]

// --- SLIDE: Simulation Lifecycle ---
#slide(title: "(2) - Simulation Lifecycle")[

  To ensure a non empty timeline start, simulation has three different stages:

  #v(0.4em)
  #col3(
    framed(title: [Stage 1: Warm-up], back-color: rgb("#e8f5e9"))[
      $t in [0, 1000]$ \
       All users online \
       Only post creation \
       Fills timelines \
    ],
    framed(title: [Stage 2: Start Up], back-color: rgb("#fff8e1"))[
      $t = 1000$ \
       Assign online/offline \
       Prime event queue \
       Session and action \
    ],
    framed(title: [Stage 3: Main Loop], back-color: rgb("#e3f2fd"))[
      $t in [1000, 5000]$ \
       Pop min-time from $Q$ \
       Dispatch to handler \
       Schedule follow-ups \
    ],
  )
]

// --- SLIDE: Implementation ---
#slide(title: "(2) - Implementation")[
  
  The simulation has been written in Zig, a systems programming language. Think C but with built in safety and QoL improvements.

  *Why?*
  1. Ensure a reasonable execution time to run the simulation multiple time, to ensure statistical significance, even for big datasets.
  2. I care about quality and my craft; it's the programmers responsability to deliver a high performance program, under _any_ circumstance.
  3. Resonable doubts about performance of other already existing simulation softwares.

  Applied *Data-oriented-Design* principles to make the program as optimal I can.
]

#slide(title: "(3) - Bluesky Data Analysis")[
  `IDea_lab` at UniGraz has recollected 1.4 years of Firehose data.

  1. Topology Obtention: processing of the full 1.4 years of data, filter the follows, unfollows and blocks to reconstruct a ($28.2 times 10^6$) user network with $1.4 times 10^9$ follows. Obtention of 7 different datasets with the *Forest Fire* algorithm: 10K, 50K, 100K, 250K, 500K, 750K, 1M. 

  2. Results Comparison & Calibration: to *obtain the value of the input parameters* 6 full days of data has been analyzed: 
  - Per user *session definition* to determine most input parameters. 
  - Post Lifetime Analysis distribution.
  - Cascade Reconstruction for every post created those 6 days and Structural Virality analysis.

  Lifetimes and Cascades will be tackled together in (5) - Results.
]

// --- SLIDE: Session Building ---
#slide(title: "(4) - Session Building")[

  The 6 day dataset contains $1.63 times 10^6$ users with at least one action. The session compute is different per each of those users.

  *Approach:* Tukey's IQR outlier detection applied per-user over their inter-event gaps. 
  
  $ "Tukey"(u) = Q_3(u) + 1.5 · (Q_3 (u) - Q_1 (u)) $


  Due to several very small sessions (one to two events), we compute the session defining that a session is *at least* 60s of lenght:

  $ delta(u) = max(120 s, thin space Q_3(u) + 1.5 dot "IQR"(u) ) $

  #v(1.0em)
  #set align(center)
  
#cetz.canvas({
  import cetz.draw: *
  
  // -----------------------------------------------------------------
  // 1. TIMELINE BASE
  // -----------------------------------------------------------------
  let timeline-y = 0
  line((0, timeline-y), (17, timeline-y), stroke: 0.75pt + luma(100))
  content((17.2, timeline-y), [$t$], anchor: "west")
  
  // -----------------------------------------------------------------
  // SESSION A: Short Cluster (3 events)
  // -----------------------------------------------------------------
  let ev1 = 0.5; let ev2 = 1.2; let ev3 = 2.2
  
  line((ev1, timeline-y - 0.1), (ev1, timeline-y + 0.1), stroke: 1pt)
  content((ev1, timeline-y + 0.2), [Lk], anchor: "south", size: 9pt)
  
  line((ev2, timeline-y - 0.1), (ev2, timeline-y + 0.1), stroke: 1pt)
  content((ev2, timeline-y + 0.2), [Rp], anchor: "south", size: 9pt)
  
  line((ev3, timeline-y - 0.1), (ev3, timeline-y + 0.1), stroke: 1pt)
  content((ev3, timeline-y + 0.2), [Cr], anchor: "south", size: 9pt)
  
  // Red Session A Span
  let s1-y = timeline-y - 0.8
  line((ev1, s1-y), (ev3, s1-y), stroke: 2pt + red)
  line((ev1, s1-y - 0.1), (ev1, s1-y + 0.1), stroke: 1.5pt + red)
  line((ev3, s1-y - 0.1), (ev3, s1-y + 0.1), stroke: 1.5pt + red)
  content(((ev1 + ev3)/2, s1-y - 0.1), [Session $A$], anchor: "north", text-color: red)

  // -----------------------------------------------------------------
  // INTER-SESSION GAP (Massive blue gap before Session B)
  // -----------------------------------------------------------------
  let ev4 = 11.0 // Large jump to start next session
  let gap-y = timeline-y - 1.8
  
  line((ev3, gap-y), (ev4, gap-y), stroke: 2pt + blue)
  line((ev3, gap-y - 0.1), (ev3, gap-y + 0.1), stroke: 1.5pt + blue)
  line((ev4, gap-y - 0.1), (ev4, gap-y + 0.1), stroke: 1.5pt + blue)
  content(((ev3 + ev4)/2, gap-y - 0.1), [Gap $>= delta(u)$ (Min 120s)], anchor: "north", text-color: blue)
  
  // Dotted vertical project line to align with the gap start/end
  line((ev3, s1-y), (ev3, gap-y), stroke: (paint: blue, dash: "dashed", thickness: 0.5pt))
  line((ev4, timeline-y), (ev4, gap-y), stroke: (paint: blue, dash: "dashed", thickness: 0.5pt))

  // -----------------------------------------------------------------
  // SESSION B: Long Cluster (5 events)
  // -----------------------------------------------------------------
  let ev5 = 12.0; let ev6 = 13.2; let ev7 = 14.5; let ev8 = 16.0
  
  line((ev4, timeline-y - 0.1), (ev4, timeline-y + 0.1), stroke: 1pt)
  content((ev4, timeline-y + 0.2), [Lk], anchor: "south", size: 9pt)
  
  line((ev5, timeline-y - 0.1), (ev5, timeline-y + 0.1), stroke: 1pt)
  content((ev5, timeline-y + 0.2), [Rp], anchor: "south", size: 9pt)
  
  line((ev6, timeline-y - 0.1), (ev6, timeline-y + 0.1), stroke: 1pt)
  content((ev6, timeline-y + 0.2), [Fl], anchor: "south", size: 9pt)

  line((ev7, timeline-y - 0.1), (ev7, timeline-y + 0.1), stroke: 1pt)
  content((ev7, timeline-y + 0.2), [Cr], anchor: "south", size: 9pt)

  line((ev8, timeline-y - 0.1), (ev8, timeline-y + 0.1), stroke: 1pt)
  content((ev8, timeline-y + 0.2), [Lk], anchor: "south", size: 9pt)
  
  // Red Session B Span
  line((ev4, s1-y), (ev8, s1-y), stroke: 2pt + red)
  line((ev4, s1-y - 0.1), (ev4, s1-y + 0.1), stroke: 1.5pt + red)
  line((ev8, s1-y - 0.1), (ev8, s1-y + 0.1), stroke: 1.5pt + red)
  content(((ev4 + ev8)/2, s1-y - 0.1), [Session $B$], anchor: "north", text-color: red)
})

]

// #slide(title: "(4) - Session Analysis")[
// #figure(
//   table(
//     columns: 2,
//     align: (left, center),
//     stroke: none,
//     table.hline(stroke: 0.8pt),
//     [*Metric*], [*sessions_all*],
//     table.hline(stroke: 0.5pt),
//     [Sessions], [$47.4 times 10^6$],
//     [Median duration], [23 s],
//     [Mean duration], [882 s],
//     [Median inter-session gap], [36.5 min],
//     [Zero-duration sessions], [33.2%],
//     [Median per-user gap], [2.4 min],
//     [Likes-only sessions], [59.2%],
//     table.hline(stroke: 0.8pt),
//   ),
//   caption: [Session-level summary statistics for `sessions_all` ($47.4 times 10^6$ sessions, $2.3 times 10^6$ users).]
// )
// ]

#slide(title: [(4) - `session_duration`, `inter-session-gap` & `inter-post creation`])[
  #figure(
    table(
      columns: 4,
      align: (left, center, center, center),
      stroke: none,
      table.hline(stroke: 0.8pt),
      [*Distribution*], [*Session duration*], [*Inter-session gap*], [*Inter-action gap*],
      table.hline(stroke: 0.5pt),
      [Power-law], [53.0%], [50.6%], [63.1%],
      [Lognormal], [9.0%], [25.9%], [21.3%],
      [Weibull], [9.5%], [22.3%], [13.8%],
      [Exponential], [12.6%], [$< 0.01$%], [-],
      [Gamma], [2.1%], [$< 0.01$%], [0.2%],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Best-fit distribution for $1.16 times 10^6$ users with $>= 10$ sessions from `sessions_all`. Power-law dominates all quantities. Vuong's log-likelihood ratio test with AIC tie-breaker.]
  )

  #set align(center)
  #v(1em)
  The parameters for every distribution have also been modeled, despite not being shown.
]

// --- SLIDE: Calibration ---
#slide(title: [(4) - Inter-action Time])[

  #set align(center)
  #text(size: 1.15em)[Only truly free input parameter: *not obtainable from data*.]
  
  #set align(left)

  Modeling "how many posts does a user see per unit of time". Should ignore most of the posts, simulate sight-reading and skipping when bored.

  #set align(center)
  #text(size: 1.3em)[*Answer*: $"Exp"(lambda), space lambda = 1/3$]
  #set align(left)

  On average, a user sees a post every three seconds. Exponential gaps $=>$ Poisson process, good sane default to guess, around 20 posts/minute.

]

#slide(title: [(4) - User Policy $pi$])[
  With the "posts/time" quantity, we can estimate *how many posts per session* does a user see and which *engagement rate*: *how many it interacts with*.


  $ "Engagement"(s) = frac("interactions"(s), "posts_seen_per_session"(s)) $

  The Engagement distribution has a median is on the *$20%$* of the density, therefore *a user interacts with 1 out of 5 posts it sees.*

  Knowing that $1/5$ posts are to be interacted, and that from all interactions on the dataset
  - likes are 93.8%
  - reposts are 6.2%

  We can define the *User Policy* as
  
  $ pi = (p_"ignore", p_"like", p_"repost") = (1 - 1/5, 1/5 · 0.938, 1/5 · 0.062) = (0.8, 0.188, 0.012) $

]

// --- SLIDE: Statistical Reproducibility ---
#slide(title: "(4) - Horizon")[

  #v(0.2em)
  #figure(
    image("images/results/100K_session_trace_stationary.png", width: 80%),
    caption: [Rolling mean of session counts over the 100K dataset horizon, used to verify stationarity of the distribution.]
  )

  With 1000 ticks of warm-up, and a 5000 ticks duraiton, we are definetly reaching stationarity.
]

#slide(title: "(5) - Parameters")[

  Input parameters:
  - horizon: 6001,
  - duration: 5000
  - warm-up: 1000
  - $pi = (p_"ignore", p_"like", p_"repost") = (0.8, 0.188, 0.012)$
  - user_inter_action: $X ~ "Exp" space E[X] = 3$
  - warmup_post_inter_creation: $U ~ "Unif"(0, 1000)$
  - propagation, interaction and creation delay: $Delta_({p, i, c})= 1$
  - offline_startup_ratio: $1/2$
  
  Userwise:
  - inter_session_time: $I ~ "Pareto"(alpha, x_min)$
  - session_length: $I ~ "Pareto"(alpha, x_min)$
  - inter_post_creation: $I ~ "Pareto"(alpha, x_min)$
  

]

#slide(title: "(4) - Experiments")[

  We have ran three datasets: 100K, 500K and 1M.

  #figure(
    table(
      columns: 3,
      align: (left, center, center),
      stroke: none,
      table.hline(stroke: 0.8pt),
      [*Dataset*], [*Users*], [*Runs*],
      table.hline(stroke: 0.5pt),
      [100K], [100,000], [1,600],
      [500K], [500,000], [136],
      [1M],   [1,000,000], [10],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Simulation runs per dataset. Fewer runs for larger topologies due to computational cost.]
  )

  Assume the figures are from the 100K dataset unless stated otherwise, as results are in the same line per the three datasets.
]

#slide(title: "(4) - Growth")[
  #image("figures/complexity_on.png", width: 100%)

  )
]

#slide(title: "(4) - Performance")[
  *Linear time growth is outstanding.*
  #v(0.15em)
  - Doubling users just "doubles" time ($R^2 = 1.000$)
  - 100K in ~1.4 min, 500K in ~10.8 min, 1M in ~22.6 min
  - *Enables massive replication without exploding runtime* Objective Achieved!

  *Quadratic memory is the bottleneck.*

  #v(0.2em)
  - Two `PagedBitSet` instances track seen and interacted posts: $N times M$ bits each
  - $M$ grows with $N$ (more users → more posts) → $O(N^2)$ worst-case
  - $100K -> 32 "GB", 500K -> 200 "GB", 1M -> 1000 "GB" approx 1"TB"$
  - Definetebly fixable with a freeing memory heuristic for dead posts!

  #v(0.4em)
  *Hardware*: 2× AMD EPYC 9654 (192c / 384t), 1.1 TB DDR5
]


#slide(title: "(4) - Total repost power-law")[
  #set text(0.85em)
  In a simulation, if we sort the posts by number of reposts, those will follow a power-law.
  Bluesky: $gamma = 2.21$ Simulation: $gamma = 1.73$

  #v(0.2em)
  #align(center)[
    #img("results/repost_comparison.png", width: 65%)
  ]

]

// --- SLIDE: Structural Virality — Simulation vs Bluesky ---
#slide(title: "(4) - Structural Virality — Model vs Data")[
  #v(0.1em)
  #figure(
    table(
      columns: 4,
      align: (left, center, center, center),
      stroke: none,
      table.hline(stroke: 0.8pt),
      [*Metric*], [*Simulation (100K)*], [*Bluesky Data*], [*Match?*],
      table.hline(stroke: 0.5pt),
      [Mean $nu$], [1.90], [1.35], [Higher],
      [Median $nu$], [1.67], [1.00], [Higher],
      [$P_95$ $nu$], [3.33], [2.98], [$approx$ same],
      [Max $nu$], [26.9], [80.7], [Lower],
      [% pure broadcast ($nu = 1.0$)], [0% (min 1.33)], [54.7%], [Missing],
      [% minimal chains ($nu <= 1.34$)], [$approx 39%$], [—], [—],
      table.hline(stroke: 0.8pt),
    ),
    caption: [Simulation (100K, $n = 1600$ runs) vs Bluesky ($4.4 times 10^6$ cascades).]
  )
]

#slide(title: "(4) - Structural Virality — Interpretation")[
  *What the model reproduces well:*
  #v(0.1em)
  - $P_95$ virality values are consistent ($3.33$ vs $2.98$)
  - The heavy right tail — rare viral cascades exist in both
  - $approx 39%$ of cascades are minimal chains — structurally simple

  #v(0.25em)
  *What the model misses:*
  #v(0.1em)
  - Pure broadcast cascades ($nu = 1.0$): 54.7% in reality, but the simulation's minimum $nu$ is $approx 1.33$ due to tree reconstruction
  - Maximum $nu$ is lower ($26.9$ vs $80.7$) — does not reach extreme viral tail
  - Homogeneous $p_"repost" = 0.012$ flattens the distribution: too many moderately branched trees, too few flat stars
]

// --- SLIDE: Timeline Starvation ---
#slide(title: "Timeline Starvation")[
  #v(0.2em)
  #text(size: 1em, weight: "bold")[An emergent phenomenon: ~50% of sessions end empty.]

  #v(0.3em)
  #col2(
    align(center)[
      #image("figures/s2_backlog_hist_100K.png", width: 100%)
      #text(size: 0.65em)[Backlog distribution (100K): zero dominates]
    ],
    [
      *The boredom mechanic:* when a user exhausts \
      their timeline, the session ends.

      - 50.9% (100K) / 45.9% (500K) / 53.0% (1M) \
        sessions end empty
      - 19–27% of sessions have *zero actions* at all
      - Root cause: timeline is cleared when user \
        goes offline
    ],
  )

  #v(0.3em)
  #text(size: 0.8em)[*Key finding:* Follower count has *no effect* on starvation — it's a timing effect, not a topological one. Sessions during quiet periods starve regardless of degree.]
]

// --- SLIDE: Session Engagement ---
#slide(title: "Session Engagement")[
  #v(0.2em)
  #text(size: 1em, weight: "bold")[Boredom bifurcates the user population.]

  #v(0.3em)
  #col2(
    align(center)[
      #image("figures/s2_duration_vs_empty_100K.png", width: 95%)
      #text(size: 0.65em)[Empty vs non-empty (100K): 9.5× difference]
    ],
    [
      *Two regimes:*
      - *Starvers:* median 12 ticks, exit empty
      - *Engagers:* median 105 ticks, stay for content

      Reposters have 2–3× longer sessions \
      than never-reposters.

      *Feedback loop:* users driving cascade propagation \
      are the same users sustaining platform engagement.
    ],
  )
]


#slide(title: "Conclusions")[
  *Model contribution.*
  #v(0.1em)
  - CTIC model + queue-based delay + activity-driven network successfully replicates information diffusion dynamics
  - High-performance DES engine ($O(N)$ time) enabled 1700+ replications across scales up to 1M users

  #v(0.3em)
  *What worked.*
  #v(0.1em)
  - Simulation reaches robust steady-state equilibrium across all scales
  - Power-law engagement tails and structural virality $P_95$ match empirical data closely
  - Repost fraction among engaged posts matches reality ($32$–$35$% vs $33.1$%)
  - Linear scalability made large-scale replication feasible
]

#slide(title: "Conclusions")[
  #v(0.1em)
  - Post homogeneity inflates moderate engagement, suppresses truly dead posts ($29$% vs $51$%)
  - Timeline starvation affects ~50% of sessions across all scales
  - Missing pure broadcast cascades due to tree reconstruction
]

#slide(title: "Future Work")[
  *Content-aware simulation.*
  #v(0.1em)
  - Replace homogeneous posts with ML embeddings (text, topic, sentiment)
  - Model homophily: users preferentially engage with content aligned to their interests
  - Heterogeneous user policies: varying repost probabilities per user

  #v(0.3em)
  *Engine improvements.*
  #v(0.1em)
  - Dynamic network topology: follows/unfollows during simulation
  - Memory freeing heuristic for dead posts → eliminate $O(N^2)$ bottleneck
]

#blank-slide[
  #set align(center)

  #text(size: 2em, weight: "bold", fill: rgb("#1a1a1a"))[Thank You]

]

#include "appendix.typ"
