"""
Generated by Gemini 3.1 Pro based on the following article: https://www.techscience.com/cmc/v73n3/49041/pdf
"""

import os
import random
import json
import polars as pl
from datetime import datetime, timedelta

def generate_social_simulator_data(num_nodes=1000, m_edges=3, cc_prob=0.8):
    # --- 1. USERS (Homogeneous Policy) ---
    # Every user shares the exact same policy and action probabilities
    users_data = []
    for i in range(num_nodes):
        users_data.append({
            'id': i,
            'actions': ["ignore", "like", "repost", "create"],
            'policy': [0.5, 0.2, 0.15, 0.15], 
        })

    # --- 2. FOLLOWERS (Plain Python Graph Generator) ---
    n0 = max(10, m_edges)
    adj = {i: [] for i in range(num_nodes)}
    
    for i in range(n0):
        left = (i - 1) % n0
        right = (i + 1) % n0
        adj[i].extend([left, right])
        
    followers_data = []
    for new_node in range(n0, num_nodes):
        targets = set()
        
        while len(targets) < m_edges:
            start_node = random.randint(0, new_node - 1)
            if not adj[start_node]: 
                continue
            
            neighbor = random.choice(adj[start_node])
            
            # Clustering Control: 1-step or 2-step walk
            if random.random() < cc_prob:
                target = neighbor 
            else:
                target = random.choice(adj[neighbor]) if adj[neighbor] else neighbor
                    
            if target != new_node and target not in targets:
                targets.add(target)
                
        for t in targets:
            followers_data.append({'follower_id': new_node, 'followed_id': t})
            adj[new_node].append(t)
            adj[t].append(new_node)

    # --- 3. POSTS & USER_OWNS_POST (DES Time Horizon) ---
    posts_data = []
    user_owns_post_data = []
    post_id_counter = 0 
    
    for user in users_data:
        # Uniform posting behavior (e.g., an average of 2 posts per user)
        num_posts = int(random.expovariate(1.0 / 2)) 
        
        for _ in range(num_posts):
            
            posts_data.append({
                'id': post_id_counter,
            })
            
            user_owns_post_data.append({
                'user_id': user['id'],
                'post_id': post_id_counter
            })
            post_id_counter += 1
            
    # Sort posts by time_created so they are strictly chronological for your event queue
    # posts_data.sort(key=lambda x: x['time'])

    # --- 4. LOAD INTO POLARS ---
    # Polars easily handles nested dictionaries for your policy column
    df_users = pl.DataFrame(users_data)
    df_followers = pl.DataFrame(followers_data)
    df_posts = pl.DataFrame(posts_data)
    df_user_owns_post = pl.DataFrame(user_owns_post_data)

    # --- 5. EXPORT TO JSON ---
    master_json = {
        "users": users_data,
        "posts": posts_data,
        "user_owns_post": user_owns_post_data,
        "followers": followers_data
    }
    
    return master_json


if __name__ == "__main__":

    os.makedirs('data', exist_ok=True)

    network_sizes = {
        "small": 1000,
        "mid": 10000,
        "large": 100000
    }

    for size_name, num_users in network_sizes.items():
        print(f"Generating '{size_name}' dataset ({num_users} users)...")
        
        # Generate the data (keeping m_edges constant gives a true scaling test)
        simulator_dataset = generate_social_simulator_data(
            num_nodes=num_users, 
            m_edges=3, 
            cc_prob=0.8
        )
        
        filename = f'data/sn_data_{size_name}.json'
        
        # Save to file
        with open(filename, 'w') as f:
            # Lowering indent to 1 (or removing it entirely) saves massive amounts of disk space for the large file
            json.dump(simulator_dataset, f, indent=1)
            
        print(f"-> Saved {size_name} dataset to {filename}!\n")

    print("All datasets generated successfully!")
