"""
Generated by Gemini 3.1 Pro based on the following article: https://www.techscience.com/cmc/v73n3/49041/pdf
"""

import os
import random
import json
import polars as pl
from datetime import datetime, timedelta

def generate_social_simulator_data(num_nodes=1000, m_edges=3, cc_prob=0.8):
    # --- 1. USERS (Homogeneous Policy) ---
    # Every user shares the exact same policy and action probabilities
    users_data = []
    for i in range(num_nodes):
        users_data.append({
            'id': i,
            'actions': ["ignore", "like", "repost" ],
            'policy': [0.5, 0.3, 0.2],
            'max_posts': 10
        })

    # --- 2. FOLLOWERS (Plain Python Graph Generator) ---
    n0 = max(10, m_edges)
    adj = {i: [] for i in range(num_nodes)}
    
    for i in range(n0):
        left = (i - 1) % n0
        right = (i + 1) % n0
        adj[i].extend([left, right])
        
    followers_data = []
    for new_node in range(n0, num_nodes):
        targets = set()
        
        while len(targets) < m_edges:
            start_node = random.randint(0, new_node - 1)
            if not adj[start_node]: 
                continue
            
            neighbor = random.choice(adj[start_node])
            
            # Clustering Control: 1-step or 2-step walk
            if random.random() < cc_prob:
                target = neighbor 
            else:
                target = random.choice(adj[neighbor]) if adj[neighbor] else neighbor
                    
            if target != new_node and target not in targets:
                targets.add(target)
                
        for t in targets:
            followers_data.append({'follower_id': new_node, 'followed_id': t})
            adj[new_node].append(t)
            adj[t].append(new_node)


    # --- 4. LOAD INTO POLARS ---
    # Polars easily handles nested dictionaries for your policy column
    df_users = pl.DataFrame(users_data)
    df_followers = pl.DataFrame(followers_data)

    # --- 5. EXPORT TO JSON ---
    master_json = {
        "users": users_data,
        "followers": followers_data
    }
    
    return master_json


if __name__ == "__main__":

    os.makedirs('data', exist_ok=True)

    network_sizes = {
        "small":    1000,
        "mid":      10000,
        "large":    100000,
        "larger":    1000000,
    }

    for size_name, num_users in network_sizes.items():
        print(f"Generating '{size_name}' dataset ({num_users} users)...")
        
        # Generate the data (keeping m_edges constant gives a true scaling test)
        simulator_dataset = generate_social_simulator_data(
            num_nodes=num_users, 
            m_edges=40, 
            cc_prob=0.8
        )
        
        filename = f'data/sn_data_{size_name}.json'
        
        # Save to file
        with open(filename, 'w') as f:
            # Lowering indent to 1 (or removing it entirely) saves massive amounts of disk space for the large file
            json.dump(simulator_dataset, f, indent=1)
            
        print(f"-> Saved {size_name} dataset to {filename}!\n")

    print("All datasets generated successfully!")
