"""The contents of this file have been generated by Gemini 3.1 Pro"""
import json
import argparse
import sys
from collections import defaultdict

def load_config(config_path):
    """Loads the simulation JSON configuration."""
    try:
        with open(config_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"Failed to load config at {config_path}: {e}")
        sys.exit(1)

def check_general_constraints(filepath):
    """
    Validates general constraints applicable to ALL trace files:
    1. time is always increasing (non-decreasing).
    2. event_id is never repeated.
    3. gen_id is never repeated.
    """
    last_time = -1.0
    seen_event_ids = set()
    seen_gen_ids = set()

    try:
        with open(filepath, 'r') as f:
            for line_num, line in enumerate(f, 1):
                if not line.strip():
                    continue
                
                data = json.loads(line)
                
                # Rule: Time always increasing
                current_time = data['time']
                if current_time < last_time:
                    print(f"[x] [General Error] {filepath} line {line_num}: Time went backwards ({current_time} < {last_time}).")
                    return False
                last_time = current_time

                # Rule: event_id not repeated
                event_id = data['event_id']
                if event_id in seen_event_ids:
                    print(f"[x] [General Error] {filepath} line {line_num}: Repeated event_id {event_id}.")
                    return False
                seen_event_ids.add(event_id)

                # Rule: gen_id not repeated
                gen_id = data['gen_id']
                if gen_id in seen_gen_ids:
                    print(f"[x] [General Error] {filepath} line {line_num}: Repeated gen_id {gen_id}.")
                    return False
                seen_gen_ids.add(gen_id)

    except FileNotFoundError:
        print(f"File not found: {filepath}")
        return False
        
    return True

def validate_create_trace(filepath, max_posts_per_user):
    """
    Validates post creation trace
    - no post_id is repeated
    - not surpasses max_post_per_user
    """
    print(f"Analyzing Create Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False

    seen_post_ids = set()
    user_post_counts = defaultdict(int)

    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip(): continue
            data = json.loads(line)
            
            post_id = data['post_id']
            user_id = data['user_id']

            # Rule: Every post_id appears exactly once
            if post_id in seen_post_ids:
                print(f"[x] [Create Error] Line {line_num}: post_id {post_id} appears more than once.")
                return False
            seen_post_ids.add(post_id)
            
            user_post_counts[user_id] += 1

    # Rule: Check against max_post_per_user (if provided)
    if max_posts_per_user is not None:
        for uid, count in user_post_counts.items():
            if count > max_posts_per_user:
                print(f"[x] [Create Error] User {uid} created {count} posts, exceeding maximum of {max_posts_per_user}.")
                return False

    print("[✓] Create Trace Passed!")
    return True

def validate_action_trace(filepath):
    """
    Validates the action trace.
    - No post can be propagated more than once by the same user
    """
    print(f"Analyzing Action Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False

    seen_reposts = set()
    
    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip(): continue
            data = json.loads(line)
            
            # Rule: No post is propagated (reposted) more than once by the same user
            if data['type'] == 'repost':
                user_id = data['user_id']
                post_id = data['post_id']
                pair = (user_id, post_id)
                
                if pair in seen_reposts:
                    print(f"❌ [Action Error] Line {line_num}: User {user_id} reposted post_id {post_id} multiple times.")
                    return False
                seen_reposts.add(pair)

    print("[✓] Action Trace Passed!")
    return True

def validate_session_trace(filepath):
    """
    Validates the session trace
    - sesisons open and close in pairs
    """
    print(f"Analyzing Session Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False

    user_session_state = {}
    
    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip(): continue
            data = json.loads(line)
            
            user_id = data['user_id']
            session_type = data['type'] # 'start' or 'end'

            # Rule: Sessions open and close in pairs
            if user_id in user_session_state:
                if user_session_state[user_id] == session_type:
                    print(f"❌ [Session Error] Line {line_num}: User {user_id} triggered consecutive '{session_type}' events without alternating.")
                    return False
            
            user_session_state[user_id] = session_type

    print("[✓] Session Trace Passed!")
    return True

def validate_causality(create_trace_path, action_trace_path, session_trace_path):
    """
    Checks that:
    - No create/action perfomed when user offline
    - No action over a post that does not exist
      """
    print("Running Causality Checks...")
    
    post_creation_times = {}
    user_online_status = defaultdict(bool) # Defaults to False
    
    # 1. Map all post creation times
    with open(create_trace_path, 'r') as f:
        for line in f:
            if not line.strip(): continue
            data = json.loads(line)
            post_creation_times[data['post_id']] = data['time']

    # 2. To check session overlap, we need to merge Actions and Sessions and sort by time.
    events = []
    
    with open(session_trace_path, 'r') as f:
        for line in f:
            if not line.strip(): continue
            data = json.loads(line)
            events.append({
                'time': data['time'],
                'event_type': 'session',
                'user_id': data['user_id'],
                'type': data['type'] # 'start' or 'end'
            })
            
    with open(action_trace_path, 'r') as f:
        for line in f:
            if not line.strip(): continue
            data = json.loads(line)
            events.append({
                'time': data['time'],
                'event_type': 'action',
                'user_id': data['user_id'],
                'post_id': data['post_id'],
                'type': data['type'] # 'like', 'repost', 'ignore'
            })

    # Sort all events strictly by time to replay the simulation
    events.sort(key=lambda x: x['time'])

    for event in events:
        user_id = event['user_id']
        
        if event['event_type'] == 'session':
            # Update user state
            user_online_status[user_id] = (event['type'] == 'start')
            
        elif event['event_type'] == 'action':
            # Check A: Is the user online?
            if not user_online_status[user_id]:
                print(f"[x] [Causality Error] User {user_id} took action '{event['type']}' while OFFLINE at time {event['time']}.")
                return False
                
            # Check B: Does the post exist yet?
            post_id = event['post_id']
            creation_time = post_creation_times.get(post_id)
            
            if creation_time is None:
                print(f"[x] [Causality Error] Action taken on post {post_id} at {event['time']}, but post was never created.")
                return False
                
            if event['time'] < creation_time:
                print(f"[x] [Causality Error] Time travel! Action on post {post_id} at {event['time']} before creation at {creation_time}.")
                return False

    print("[✓] Causality Checks Passed!")
    return True

def validate_topology(create_trace_path, action_trace_path, graph_export_path):
    """
    Validates underlying network structure when a repost occurs
    Repost must make appear to just the followers.
    If a post appears without the followers it must be from a direct follower
    """
    print("Running Topology Checks...")
    
    # Load the raw network JSON
    with open(graph_export_path, 'r') as f:
        raw_network = json.load(f)
        
    # Build the adjacency list dynamically: { str(author_id): [follower_id, follower_id, ...] }
    graph = {}
    for edge in raw_network.get('followers', []):
        follower = edge['follower_id']
        followed = edge['followed_id']
        
        # The author is the 'followed_id', their audience is the 'follower_id'
        str_author = str(followed)
        if str_author not in graph:
            graph[str_author] = []
        graph[str_author].append(follower)
        
    # Map post_id to its original author
    post_authors = {}
    with open(create_trace_path, 'r') as f:
        for line in f:
            if not line.strip(): continue
            data = json.loads(line)
            post_authors[data['post_id']] = data['user_id']

    # Track which posts have been reposted to open up the topology
    reposted_posts = set()
    
    with open(action_trace_path, 'r') as f:
        for line in f:
            if not line.strip(): continue
            data = json.loads(line)
            
            post_id = data['post_id']
            user_id = data['user_id']
            action_type = data['type']
            
            author_id = post_authors[post_id]
            
            # Fetch the author's followers (default to empty list if they have none)
            author_followers = graph.get(str(author_id), [])
            
            # The author implicitly "follows" themselves to pass the matrix check
            if author_id not in author_followers:
                author_followers.append(author_id)
                
            # If this post hasn't been reposted yet, the user seeing it MUST follow the author
            if post_id not in reposted_posts:
                if user_id not in author_followers:
                    print(f"[x] [Topology Error] User {user_id} saw post {post_id} by author {author_id}, but does not follow them and no reposts exist yet.")
                    return False
            
            # If the action is a repost, mark it so we know it has spread beyond direct followers
            if action_type == 'repost':
                reposted_posts.add(post_id)

    print("[✓] Topology Invariance Passed!")
    return True

def main():
    parser = argparse.ArgumentParser(description="Validate Zig Simulation Traces")
    parser.add_argument("config", type=str, help="Path to sim config JSON")
    parser.add_argument("graph", type=str, help="Path to graph data")
    parser.add_argument("create", type=str, help="Path to create trace JSONL")
    parser.add_argument("action", type=str, help="Path to action trace JSONL")
    parser.add_argument("session", type=str, help="Path to session trace JSONL")
    parser.add_argument("--max-posts", type=int, default=None, help="Max posts per user (optional override)")
    
    args = parser.parse_args()

    config = load_config(args.config)
    print(f"Configuration loaded successfully. (File: {args.config})\n")

    # If max_posts is explicitly in config, grab it. Otherwise, rely on CLI argument.
    max_posts_per_user = args.max_posts
    if 'max_posts_per_user' in config and max_posts_per_user is None:
        max_posts_per_user = config['max_posts_per_user']

    # Run Baseline Validations
    create_valid = validate_create_trace(args.create, max_posts_per_user)
    action_valid = validate_action_trace(args.action)
    session_valid = validate_session_trace(args.session)
    
    causality_valid = validate_causality(args.create, args.action, args.session)
    
    topology_valid = True
    topology_valid = validate_topology(args.create, args.action, args.graph)

    print("\n--- Summary ---")
    all_passed = all([create_valid, action_valid, session_valid, causality_valid, topology_valid])
    
    if all_passed:
        print("[ ] All traces and physics rules are perfectly valid!")
        sys.exit(0)
    else:
        print("[x] One or more traces failed validation.")
        sys.exit(1)

if __name__ == "__main__":
    main()
