"""The contents of this file have been generated by Gemini 3.1 Pro"""

# The contents of this file have been upgraded to support explicit propagation traces
import json
import argparse
import sys
from collections import defaultdict


def load_config(config_path):
    """Loads the simulation JSON configuration."""
    try:
        with open(config_path, "r") as f:
            return json.load(f)
    except Exception as e:
        print(f"Failed to load config at {config_path}: {e}")
        sys.exit(1)


def check_general_constraints(filepath):
    """
    Validates general constraints applicable to ALL trace files:
    1. time is always increasing (non-decreasing).
    2. event_id is never repeated.
    3. gen_id is never repeated.
    """
    last_time = -1.0
    seen_event_ids = set()
    seen_gen_ids = set()

    try:
        with open(filepath, "r") as f:
            for line_num, line in enumerate(f, 1):
                if not line.strip():
                    continue

                data = json.loads(line)

                # Rule: Time always increasing
                current_time = data["time"]
                if current_time < last_time:
                    print(
                        f"[x] [General Error] {filepath} line {line_num}: Time went backwards ({current_time} < {last_time})."
                    )
                    return False
                last_time = current_time

                # Rule: event_id not repeated
                event_id = data["event_id"]
                if event_id in seen_event_ids:
                    print(
                        f"[x] [General Error] {filepath} line {line_num}: Repeated event_id {event_id}."
                    )
                    return False
                seen_event_ids.add(event_id)

                # Rule: gen_id not repeated
                gen_id = data["gen_id"]
                if gen_id in seen_gen_ids:
                    print(
                        f"[x] [General Error] {filepath} line {line_num}: Repeated gen_id {gen_id}."
                    )
                    return False
                seen_gen_ids.add(gen_id)

    except FileNotFoundError:
        print(f"File not found: {filepath}")
        return False

    return True


def validate_create_trace(filepath, max_posts_per_user):
    print(f"Analyzing Create Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False

    seen_post_ids = set()
    user_post_counts = defaultdict(int)

    with open(filepath, "r") as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue
            data = json.loads(line)

            post_id = data["post_id"]
            user_id = data["user_id"]

            if post_id in seen_post_ids:
                print(
                    f"[x] [Create Error] Line {line_num}: post_id {post_id} appears more than once."
                )
                return False
            seen_post_ids.add(post_id)

            user_post_counts[user_id] += 1

    if max_posts_per_user is not None:
        for uid, count in user_post_counts.items():
            if count > max_posts_per_user:
                print(
                    f"[x] [Create Error] User {uid} created {count} posts, exceeding maximum of {max_posts_per_user}."
                )
                return False

    print("[✓] Create Trace Passed!")
    return True


def validate_action_trace(filepath):
    print(f"Analyzing Action Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False

    seen_reposts = set()

    with open(filepath, "r") as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue
            data = json.loads(line)

            if data["type"] in ("repost", "quote"):
                user_id = data["user_id"]
                post_id = data["post_id"]
                pair = (user_id, post_id)

                if pair in seen_reposts:
                    print(
                        f"❌ [Action Error] Line {line_num}: User {user_id} reposted post_id {post_id} multiple times."
                    )
                    return False
                seen_reposts.add(pair)

    print("[✓] Action Trace Passed!")
    return True


def validate_session_trace(filepath):
    print(f"Analyzing Session Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False

    user_session_state = {}

    with open(filepath, "r") as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue
            data = json.loads(line)

            user_id = data["user_id"]
            session_type = data["type"]

            if user_id in user_session_state:
                if user_session_state[user_id] == session_type:
                    print(
                        f"❌ [Session Error] Line {line_num}: User {user_id} triggered consecutive '{session_type}' events without alternating."
                    )
                    return False

            user_session_state[user_id] = session_type

    print("[✓] Session Trace Passed!")
    return True


def validate_propagate_trace(filepath):
    print(f"Analyzing Propagate Trace: {filepath}...")
    if not check_general_constraints(filepath):
        return False
    print("[✓] Propagate Trace Passed!")
    return True


def validate_causality(create_trace_path, action_trace_path, session_trace_path):
    print("Running Causality Checks...")

    post_creation_times = {}
    user_online_status = defaultdict(bool)

    with open(create_trace_path, "r") as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            post_creation_times[data["post_id"]] = data["time"]

    events = []

    with open(session_trace_path, "r") as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            events.append(
                {
                    "time": data["time"],
                    "event_type": "session",
                    "user_id": data["user_id"],
                    "type": data["type"],
                }
            )

    with open(action_trace_path, "r") as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            events.append(
                {
                    "time": data["time"],
                    "event_type": "action",
                    "user_id": data["user_id"],
                    "post_id": data["post_id"],
                    "type": data["type"],
                }
            )

    events.sort(key=lambda x: x["time"])

    for event in events:
        user_id = event["user_id"]

        if event["event_type"] == "session":
            user_online_status[user_id] = event["type"] == "start"

        elif event["event_type"] == "action":
            if not user_online_status[user_id]:
                print(
                    f"[x] [Causality Error] User {user_id} took action '{event['type']}' while OFFLINE at time {event['time']}."
                )
                return False

            post_id = event["post_id"]
            creation_time = post_creation_times.get(post_id)

            if creation_time is None:
                print(
                    f"[x] [Causality Error] Action taken on post {post_id} at {event['time']}, but post was never created."
                )
                return False

            if event["time"] < creation_time:
                print(
                    f"[x] [Causality Error] Time travel! Action on post {post_id} at {event['time']} before creation at {creation_time}."
                )
                return False

    print("[✓] Causality Checks Passed!")
    return True


def validate_topology(
    create_trace_path, action_trace_path, propagate_trace_path, graph_export_path
):
    print("Running Deterministic Topology Checks...")

    # 1. Build the adjacency list: { "author_id": ["follower_id", ...] }
    with open(graph_export_path, "r") as f:
        raw_network = json.load(f)

    graph = {}
    for edge in raw_network.get("followers", []):
        # STRICT CASTING: Enforce strings for all IDs
        follower = str(edge["follower_id"])
        followed = str(edge["followed_id"])

        if followed not in graph:
            graph[followed] = []
        graph[followed].append(follower)

    # 2. Map post_id to its original author
    post_authors = {}
    with open(create_trace_path, "r") as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            post_authors[str(data["post_id"])] = str(data["user_id"])

    # 3. Combine Propagate and Action events
    events = []
    with open(propagate_trace_path, "r") as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            post_id = str(data.get("post_id", data.get("type")))
            events.append(
                {
                    "time": float(data["time"]),
                    "event_type": "propagate",
                    "user_id": str(data["user_id"]),
                    "post_id": post_id,
                }
            )

    with open(action_trace_path, "r") as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            events.append(
                {
                    "time": float(data["time"]),
                    "event_type": "action",
                    "user_id": str(data["user_id"]),
                    "post_id": str(data["post_id"]),
                }
            )

    # Sort strictly by time. If tie, process 'propagate' before 'action'.
    events.sort(key=lambda x: (x["time"], 0 if x["event_type"] == "propagate" else 1))

    # Track who has propagated what: { "post_id": set("user_id") }
    active_propagators = defaultdict(set)

    for event in events:
        post_id = event["post_id"]
        user_id = event["user_id"]

        if event["event_type"] == "propagate":
            active_propagators[post_id].add(user_id)

        elif event["event_type"] == "action":
            valid_source = False

            # Safeguard: The author is always allowed to see their own post
            if user_id == post_authors.get(post_id):
                valid_source = True
            else:
                # User MUST follow at least one person who has already propagated this post
                for propagator in active_propagators[post_id]:
                    if user_id in graph.get(propagator, []):
                        valid_source = True
                        break

            if not valid_source:
                print(
                    f"[x] [Topology Error] User {user_id} acted on post {post_id} at time {event['time']}."
                )
                print(f"    -> They do not follow any valid propagator.")
                print(f"    -> Author of this post: {post_authors.get(post_id)}")
                print(
                    f"    -> Active propagators so far: {list(active_propagators[post_id])}"
                )
                return False

    print("[✓] Topology Invariance Passed!")
    return True


def main():
    parser = argparse.ArgumentParser(description="Validate Zig Simulation Traces")
    parser.add_argument("config", type=str, help="Path to sim config JSON")
    parser.add_argument("graph", type=str, help="Path to graph data")
    parser.add_argument("create", type=str, help="Path to create trace JSONL")
    parser.add_argument("action", type=str, help="Path to action trace JSONL")
    parser.add_argument("session", type=str, help="Path to session trace JSONL")
    parser.add_argument("propagate", type=str, help="Path to propagate trace JSONL")
    parser.add_argument(
        "--max-posts",
        type=int,
        default=None,
        help="Max posts per user (optional override)",
    )

    args = parser.parse_args()

    config = load_config(args.config)
    print(f"Configuration loaded successfully. (File: {args.config})\n")

    max_posts_per_user = args.max_posts
    if "max_posts_per_user" in config and max_posts_per_user is None:
        max_posts_per_user = config["max_posts_per_user"]

    # Run Baseline Validations
    create_valid = validate_create_trace(args.create, max_posts_per_user)
    action_valid = validate_action_trace(args.action)
    session_valid = validate_session_trace(args.session)
    propagate_valid = validate_propagate_trace(args.propagate)

    causality_valid = validate_causality(args.create, args.action, args.session)

    topology_valid = validate_topology(
        args.create, args.action, args.propagate, args.graph
    )

    print("\n--- Summary ---")
    all_passed = all(
        [
            create_valid,
            action_valid,
            session_valid,
            propagate_valid,
            causality_valid,
            topology_valid,
        ]
    )

    if all_passed:
        print("[✓] All traces and physics rules are perfectly valid!")
        sys.exit(0)
    else:
        print("[x] One or more traces failed validation.")
        sys.exit(1)


if __name__ == "__main__":
    main()
